/*
 * *************************************************************************
 * The contents of this file are subject to the Etendo License
 * (the "License"), you may not use this file except in compliance with
 * the License.
 * You may obtain a copy of the License at
 * https://github.com/etendosoftware/etendo_core/blob/main/legal/Etendo_license.txt
 * Software distributed under the License is distributed on an
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing rights
 * and limitations under the License.
 * All portions are Copyright (C) 2021-2026 FUTIT SERVICES, S.L
 * All Rights Reserved.
 * Contributor(s): Futit Services S.L.
 * *************************************************************************
 */

package com.etendoerp.go.schemaforge.util;

import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;

import com.etendoerp.go.schemaforge.data.SFEntity;
import com.etendoerp.go.schemaforge.data.SFSpec;

/**
 * Shared report-callability logic for report-type specs (specType = "R").
 *
 * <p>Per ETP-4255, Etendo Go / NEO Headless / MCP must never execute Jasper,
 * JRXML, classic AD_Process report execution, or {@code ReportingUtils.exportJR}.
 * A report spec is callable only when it is backed by a NEO-native report handler
 * (a {@code NeoHandler} CDI bean matched by the {@code Java_Qualifier} declared on
 * one of the spec's entities). Report specs without such a handler are exposed as
 * non-callable with a stable {@code not_configured_for_report_generation} status,
 * identical across MCP discover, the MCP report tool, and the NEO HTTP endpoint.</p>
 *
 * <p>Jasper migration metadata is preserved only in offline Schema Forge tooling;
 * it never implies runtime report execution by Etendo Go.</p>
 */
public final class NeoReportCallability {

  private static final Logger log = LogManager.getLogger(NeoReportCallability.class);

  /** Stable status string for a report spec that cannot be generated by Etendo Go/MCP. */
  public static final String STATUS_NOT_CONFIGURED = "not_configured_for_report_generation";

  private NeoReportCallability() {
  }

  /**
   * Resolve the NEO-native report handler qualifier for the spec: the first non-blank
   * {@code Java_Qualifier} among the spec's entities.
   *
   * @param spec the report spec to inspect
   * @return the handler qualifier, or {@code null} when the spec has no NEO-native handler
   */
  public static String resolveReportHandlerQualifier(SFSpec spec) {
    try {
      OBCriteria<SFEntity> criteria = OBDal.getInstance().createCriteria(SFEntity.class);
      criteria.add(Restrictions.eq(SFEntity.PROPERTY_ETGOSFSPEC + ".id", spec.getId()));
      List<SFEntity> entities = criteria.list();
      for (SFEntity entity : entities) {
        String qualifier = entity.getJavaQualifier();
        if (StringUtils.isNotBlank(qualifier)) {
          return qualifier;
        }
      }
    } catch (Exception e) {
      log.warn("Error resolving report handler qualifier for spec '{}': {}",
          spec.getName(), e.getMessage());
    }
    return null;
  }

  /**
   * Reports whether the given report spec is callable, i.e. backed by a NEO-native report
   * handler resolved via its {@code Java_Qualifier}.
   *
   * @param spec the report spec to inspect
   * @return {@code true} when the spec is backed by a NEO-native report handler and can
   *         therefore be generated by Etendo Go/MCP
   */
  public static boolean isReportCallable(SFSpec spec) {
    return resolveReportHandlerQualifier(spec) != null;
  }

  /**
   * Build the stable non-callable message for a report spec that is not configured for
   * Etendo Go/MCP report generation. Identical text is returned by MCP discover, the MCP
   * report tool, and the NEO HTTP endpoint.
   *
   * @param specName the report spec name
   * @return the canonical human-readable message
   */
  public static String buildNotConfiguredMessage(String specName) {
    return "Report spec '" + specName + "' is not configured for Etendo Go/MCP report "
        + "generation. Jasper/AD_Process reports are legacy migration sources only and "
        + "cannot be generated by Etendo Go. Configure a NEO report handler to enable it.";
  }

  /**
   * Build the canonical non-callable JSON body for a report spec, used identically by MCP
   * discover, the MCP report tool, and the NEO HTTP endpoint (returned with HTTP 200).
   *
   * @param specName the report spec name
   * @return JSON: {@code {name, type:"report", callable:false, status, message}}
   * @throws JSONException if JSON assembly fails
   */
  public static JSONObject buildNotConfiguredResponse(String specName) throws JSONException {
    JSONObject body = new JSONObject();
    body.put("name", specName);
    body.put("type", "report");
    body.put("callable", false);
    body.put("status", STATUS_NOT_CONFIGURED);
    body.put("message", buildNotConfiguredMessage(specName));
    return body;
  }
}
