/*
 * *************************************************************************
 * The contents of this file are subject to the Etendo License
 * (the "License"), you may not use this file except in compliance with
 * the License.
 * You may obtain a copy of the License at
 * https://github.com/etendosoftware/etendo_core/blob/main/legal/Etendo_license.txt
 * Software distributed under the License is distributed on an
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing rights
 * and limitations under the License.
 * All portions are Copyright (C) 2021-2026 FUTIT SERVICES, S.L
 * All Rights Reserved.
 * Contributor(s): Futit Services S.L.
 * *************************************************************************
 */

package com.etendoerp.go.schemaforge.email;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

/**
 * Document metadata used to resolve a transactional email recipient and payload.
 */
public final class EmailDocumentRecord {

  private final String recipientName;
  private final String recipientEmail;
  private final String recordId;
  private final String documentNumber;
  private final String amount;
  private final String downloadLink;
  private final String clientId;
  private final List<EmailDocumentDetail> details;

  /**
   * Creates a document record whose download link must be generated by the email contract.
   *
   * @param recipientName display name for the server-resolved recipient
   * @param recipientEmail email address for the server-resolved recipient
   * @param recordId trusted document record id
   * @param documentNumber human-readable document number
   * @param amount formatted amount for templates that include totals
   * @param clientId trusted client id that owns the document
   * @return document email record without a prebuilt server download link
   */
  public static EmailDocumentRecord withGeneratedDownloadLink(final String recipientName,
      final String recipientEmail, final String recordId, final String documentNumber,
      final String amount, final String clientId) {
    return new EmailDocumentRecord(recipientName, recipientEmail, recordId, documentNumber,
        amount, null, clientId);
  }

  /**
   * Creates a document record that also carries the rows of the email's summary block.
   *
   * @param recipientName display name for the server-resolved recipient
   * @param recipientEmail email address for the server-resolved recipient
   * @param recordId trusted document record id
   * @param documentNumber human-readable document number
   * @param amount formatted amount for templates that include totals
   * @param clientId trusted client id that owns the document
   * @param details summary rows in render order; rows without a value are dropped
   * @return document email record without a prebuilt server download link
   */
  public static EmailDocumentRecord withGeneratedDownloadLink(final String recipientName,
      final String recipientEmail, final String recordId, final String documentNumber,
      final String amount, final String clientId, final List<EmailDocumentDetail> details) {
    return withGeneratedDownloadLink(recipientName, recipientEmail, recordId, documentNumber,
        amount, clientId).withDetails(details);
  }

  /**
   * Creates a normalized document email record.
   *
   * @param recipientName display name for the server-resolved recipient
   * @param recipientEmail email address for the server-resolved recipient
   * @param recordId trusted document record id
   * @param documentNumber human-readable document number
   * @param amount formatted amount for templates that include totals
   * @param downloadLink absolute server link used by the template, or {@code null} when the
   *        contract must generate a signed download link
   * @param clientId trusted client id that owns the document
   */
  public EmailDocumentRecord(final String recipientName, final String recipientEmail,
      final String recordId, final String documentNumber, final String amount,
      final String downloadLink, final String clientId) {
    this.details = Collections.emptyList();
    this.recipientName = StringUtils.trimToNull(recipientName);
    this.recipientEmail = StringUtils.trimToNull(recipientEmail);
    this.recordId = StringUtils.trimToNull(recordId);
    this.documentNumber = StringUtils.trimToNull(documentNumber);
    this.amount = StringUtils.trimToNull(amount);
    this.downloadLink = StringUtils.trimToNull(downloadLink);
    this.clientId = StringUtils.trimToNull(clientId);
  }

  /**
   * Creates a normalized document email record without a trusted document record id.
   * <p>
   * This constructor is kept for compatibility with callers that already provide a download link.
   * New document send contracts should prefer {@link #withGeneratedDownloadLink(String, String,
   * String, String, String, String)} or the constructor that receives {@code recordId}.
   *
   * @param recipientName display name for the server-resolved recipient
   * @param recipientEmail email address for the server-resolved recipient
   * @param documentNumber human-readable document number
   * @param amount formatted amount for templates that include totals
   * @param downloadLink absolute server link used by the template
   * @param clientId trusted client id that owns the document
   */
  public EmailDocumentRecord(final String recipientName, final String recipientEmail,
      final String documentNumber, final String amount, final String downloadLink,
      final String clientId) {
    this(recipientName, recipientEmail, null, documentNumber, amount, downloadLink, clientId);
  }

  public String getRecipientName() {
    return recipientName;
  }

  public String getRecipientEmail() {
    return recipientEmail;
  }

  /**
   * @return trusted document record id, when the resolver can provide it
   */
  public String getRecordId() {
    return recordId;
  }

  public String getDocumentNumber() {
    return documentNumber;
  }

  public String getAmount() {
    return amount;
  }

  public String getDownloadLink() {
    return downloadLink;
  }

  public String getClientId() {
    return clientId;
  }

  /**
   * Rows of the email's summary block, in render order.
   *
   * @return the details, never {@code null}; empty when the document shows no summary block
   */
  public List<EmailDocumentDetail> getDetails() {
    return details;
  }

  /**
   * Returns a copy of this record carrying the given summary rows.
   *
   * <p>Separate from the constructors on purpose: threading the rows through them would push the
   * widest one past the parameter count anybody can read at a glance, for a value most callers do
   * not set.</p>
   *
   * @param details summary rows in render order; rows without a value are dropped
   * @return a record identical to this one except for its details
   */
  public EmailDocumentRecord withDetails(final List<EmailDocumentDetail> details) {
    return new EmailDocumentRecord(this, details);
  }

  private EmailDocumentRecord(final EmailDocumentRecord source,
      final List<EmailDocumentDetail> details) {
    this.recipientName = source.recipientName;
    this.recipientEmail = source.recipientEmail;
    this.recordId = source.recordId;
    this.documentNumber = source.documentNumber;
    this.amount = source.amount;
    this.downloadLink = source.downloadLink;
    this.clientId = source.clientId;
    this.details = normalizeDetails(details);
  }

  private static List<EmailDocumentDetail> normalizeDetails(
      final List<EmailDocumentDetail> source) {
    if (source == null || source.isEmpty()) {
      return Collections.emptyList();
    }
    List<EmailDocumentDetail> normalized = new ArrayList<>(source.size());
    for (EmailDocumentDetail detail : source) {
      if (detail != null && detail.hasValue()) {
        normalized.add(detail);
      }
    }
    return Collections.unmodifiableList(normalized);
  }
}
