sonar.projectKey=etendosoftware_com.etendoerp.go_4f22c2cf-5ab2-4734-8244-f9eb74bbbb7a
sonar.sources=src
sonar.tests=src-test/src
sonar.exclusions=app.log,src-db/database/model/**,src-db/database/sourcedata/**,referencedata/**
sonar.test.inclusions=src-test/src/**/*.java
sonar.cpd.exclusions=src-test/src/**,src-db/database/sourcedata/**,src-db/database/model/**,referencedata/**
sonar.java.binaries=.
