// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.validation;

import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.exception.OBException;
import org.openbravo.model.common.order.Order;

/**
 * Precondition Validator: CopyLinesValidator
 *
 * Entity: cOrder (Order)
 * Preconditions: 2
 */
public class CopyLinesValidator {

  private static final Logger log = LogManager.getLogger();

  /**
   * Validate all preconditions for the given entity.
   *
   * @param entity the Order to validate
   * @throws OBException if any precondition fails
   */
  public void validate(Order entity) {
    final List<String> errors = new ArrayList<>();

    // PRE-CL-001: order.docStatus == 'DR'
    // TODO(vertical-slice): implement precondition check
    // Expected error: Target order must be in Draft status to copy lines into it
    // PRE-CL-002: sourceOrderIds.length > 0
    // TODO(vertical-slice): implement precondition check
    // Expected error: At least one source order must be selected

    if (!errors.isEmpty()) {
      throw new OBException(String.join("; ", errors));
    }
  }
}
