// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.validation;

import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.exception.OBException;
import org.openbravo.base.structure.BaseOBObject;

/**
 * Precondition Validator: PostOrderValidator
 *
 * Validates entity state before process execution.
 * Preconditions: 2
 */
public class PostOrderValidator {

  private static final Logger log = LogManager.getLogger();

  /**
   * Validate all preconditions for the given entity.
   *
   * @param entity the entity to validate
   * @throws OBException if any precondition fails
   */
  public void validate(BaseOBObject entity) {
    final List<String> errors = new ArrayList<>();

    // PRE-POST-001: order.processed == true
    // TODO(vertical-slice): implement precondition check
    // Expected error: Order must be processed (completed or voided) before posting
    // PRE-POST-002: userPreferences.showAccounting == true
    // TODO(vertical-slice): implement precondition check
    // Expected error: User must have Show Accounting preference enabled

    if (!errors.isEmpty()) {
      throw new OBException(String.join("; ", errors));
    }
  }
}
