// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.validation;

import java.util.ArrayList;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.exception.OBException;
import org.openbravo.model.common.order.Order;

/**
 * Precondition Validator: ProcessOrderValidator
 *
 * Entity: cOrder (Order)
 * Preconditions: 3
 */
public class ProcessOrderValidator {

  private static final Logger log = LogManager.getLogger();

  /**
   * Validate all preconditions for the given entity.
   *
   * @param entity the Order to validate
   * @throws OBException if any precondition fails
   */
  public void validate(Order entity) {
    final List<String> errors = new ArrayList<>();

    // PRE-PO-001: order.docStatus IN ('DR', 'IP')
    // TODO(vertical-slice): implement precondition check
    // Expected error: Order must be in Draft or In Progress status to complete
    // PRE-PO-002: order.lines.length > 0
    // TODO(vertical-slice): implement precondition check
    // Expected error: Order must have at least one line
    // PRE-PO-003: order.businessPartner.currency != null
    // TODO(vertical-slice): implement precondition check
    // Expected error: Business partner must have a currency configured before completion

    if (!errors.isEmpty()) {
      throw new OBException(String.join("; ", errors));
    }
  }
}
