/*
 * *************************************************************************
 * The contents of this file are subject to the Etendo License
 * (the "License"), you may not use this file except in compliance with
 * the License.
 * You may obtain a copy of the License at
 * https://github.com/etendosoftware/etendo_core/blob/main/legal/Etendo_license.txt
 * Software distributed under the License is distributed on an
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing rights
 * and limitations under the License.
 * All portions are Copyright (C) 2021-2026 FUTIT SERVICES, S.L
 * All Rights Reserved.
 * Contributor(s): Futit Services S.L.
 * *************************************************************************
 */
package com.etendoerp.go.onboarding;

import java.util.Map;

/**
 * The two passes {@link OnboardingDatasetNormalizer} can make over the GOClient sourcedata.
 *
 * <p>Both read the same files; they differ in which tables they open, which rows they keep, which
 * columns they strip and which values they rewrite.
 */
enum OnboardingDatasetProfile {

  /** The curated configuration and master data every new tenant receives. */
  ONBOARDING {
    @Override
    boolean includesTable(String tableName) {
      return OnboardingDatasetDefinition.shouldIncludeTable(tableName);
    }

    @Override
    boolean isStrippedColumn(String tableName, String columnName) {
      return OnboardingDatasetDefinition.isStrippedColumn(tableName, columnName);
    }

    @Override
    String rewriteValue(String columnName, String rawValue) {
      return rawValue;
    }

    @Override
    boolean keepsClientLevelOrganization() {
      return true;
    }

    @Override
    Map<String, String> addedColumns(String tableName, Map<String, String> rawColumns) {
      return Map.of();
    }
  },

  /** ETP-5426 — the optional sample data; see {@link OnboardingSampleDataDefinition}. */
  SAMPLE_DATA {
    @Override
    boolean includesTable(String tableName) {
      return OnboardingSampleDataDefinition.includesTable(tableName);
    }

    @Override
    boolean isStrippedColumn(String tableName, String columnName) {
      return OnboardingDatasetDefinition.isStrippedColumn(tableName, columnName)
          || OnboardingSampleDataDefinition.isStrippedColumn(tableName, columnName);
    }

    @Override
    String rewriteValue(String columnName, String rawValue) {
      return OnboardingSampleDataDefinition.rewriteValue(columnName, rawValue);
    }

    /**
     * Sample data is business data, so every row belongs to the tenant's business organization —
     * where a user creating the same record in the app would put it. Keeping GOClient's
     * client-level rows at {@code '0'} breaks the import: {@code C_BPartner.EM_Etgo_Identifier} is
     * generated by a transactional sequence that onboarding only creates for the business
     * organization, so a partner at {@code '0'} fails with "No sequence found".
     */
    @Override
    boolean keepsClientLevelOrganization() {
      return false;
    }

    @Override
    Map<String, String> addedColumns(String tableName, Map<String, String> rawColumns) {
      return OnboardingSampleDataDefinition.addedColumns(tableName, rawColumns);
    }
  };

  /**
   * @param tableName the sourcedata table name
   * @return whether this pass reads the table's file
   */
  abstract boolean includesTable(String tableName);

  /**
   * @param tableName  the sourcedata table name
   * @param columnName the column name
   * @return whether the column is left out of the normalized row
   */
  abstract boolean isStrippedColumn(String tableName, String columnName);

  /**
   * @param columnName the column name
   * @param rawValue   the trimmed, non-empty sourcedata value
   * @return the value to import
   */
  abstract String rewriteValue(String columnName, String rawValue);

  /**
   * @return whether a row owned by the client-level organization ({@code '0'}) keeps it, instead of
   *     being moved to the target organization like every other row
   */
  abstract boolean keepsClientLevelOrganization();

  /**
   * @param tableName  the sourcedata table name
   * @param rawColumns the row's raw sourcedata columns, keys upper-cased
   * @return column values to add to the row because the source leaves them empty, keyed by
   *     upper-cased column name
   */
  abstract Map<String, String> addedColumns(String tableName, Map<String, String> rawColumns);
}
