// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.COrderReplacementDTO;

/**
 * Etendo RX Endpoint: COrderReplacementEndpoint
 *
 * Provides REST API for cOrderReplacement entity with org-level filtering.
 */
@Path("/cOrderReplacement")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class COrderReplacementEndpoint {

  @GET
  public Response list(
    @QueryParam("cReplacementId") String cReplacementId
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<cOrderReplacement> criteria = OBDal.getInstance()
          .createCriteria(cOrderReplacement.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (cReplacementId != null) {
        criteria.add(Restrictions.eq("C_Replacement_ID", cReplacementId));
      }

      final List<cOrderReplacement> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderReplacementDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final cOrderReplacement entity = OBDal.getInstance().get(cOrderReplacement.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderReplacementDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
