// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.COrderLineDTO;

/**
 * Etendo RX Endpoint: COrderLineEndpoint
 *
 * Provides REST API for cOrderLine entity with org-level filtering.
 */
@Path("/cOrderLine")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class COrderLineEndpoint {

  @GET
  public Response list(
    @QueryParam("mProductId") String mProductId,
    @QueryParam("cAum") String cAum,
    @QueryParam("cUomId") String cUomId,
    @QueryParam("priceActual") String priceActual,
    @QueryParam("grossUnitPrice") String grossUnitPrice,
    @QueryParam("cTaxId") String cTaxId,
    @QueryParam("priceList") String priceList,
    @QueryParam("mWarehouseRuleId") String mWarehouseRuleId,
    @QueryParam("replacedorderlineId") String replacedorderlineId,
    @QueryParam("mProductUomId") String mProductUomId,
    @QueryParam("priceStd") String priceStd,
    @QueryParam("grosspricestd") String grosspricestd,
    @QueryParam("quotationlineId") String quotationlineId,
    @QueryParam("cProjectId") String cProjectId,
    @QueryParam("cCostcenterId") String cCostcenterId,
    @QueryParam("aAssetId") String aAssetId,
    @QueryParam("user1Id") String user1Id,
    @QueryParam("user2Id") String user2Id
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<cOrderLine> criteria = OBDal.getInstance()
          .createCriteria(cOrderLine.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (mProductId != null) {
        criteria.add(Restrictions.eq("M_Product_ID", mProductId));
      }
      if (cAum != null) {
        criteria.add(Restrictions.eq("C_Aum", cAum));
      }
      if (cUomId != null) {
        criteria.add(Restrictions.eq("C_UOM_ID", cUomId));
      }
      if (priceActual != null) {
        criteria.add(Restrictions.eq("PriceActual", priceActual));
      }
      if (grossUnitPrice != null) {
        criteria.add(Restrictions.eq("Gross_Unit_Price", grossUnitPrice));
      }
      if (cTaxId != null) {
        criteria.add(Restrictions.eq("C_Tax_ID", cTaxId));
      }
      if (priceList != null) {
        criteria.add(Restrictions.eq("PriceList", priceList));
      }
      if (mWarehouseRuleId != null) {
        criteria.add(Restrictions.eq("M_Warehouse_Rule_ID", mWarehouseRuleId));
      }
      if (replacedorderlineId != null) {
        criteria.add(Restrictions.eq("Replacedorderline_id", replacedorderlineId));
      }
      if (mProductUomId != null) {
        criteria.add(Restrictions.eq("M_Product_Uom_Id", mProductUomId));
      }
      if (priceStd != null) {
        criteria.add(Restrictions.eq("PriceStd", priceStd));
      }
      if (grosspricestd != null) {
        criteria.add(Restrictions.eq("grosspricestd", grosspricestd));
      }
      if (quotationlineId != null) {
        criteria.add(Restrictions.eq("Quotationline_ID", quotationlineId));
      }
      if (cProjectId != null) {
        criteria.add(Restrictions.eq("C_Project_ID", cProjectId));
      }
      if (cCostcenterId != null) {
        criteria.add(Restrictions.eq("C_Costcenter_ID", cCostcenterId));
      }
      if (aAssetId != null) {
        criteria.add(Restrictions.eq("A_Asset_ID", aAssetId));
      }
      if (user1Id != null) {
        criteria.add(Restrictions.eq("User1_ID", user1Id));
      }
      if (user2Id != null) {
        criteria.add(Restrictions.eq("User2_ID", user2Id));
      }

      final List<cOrderLine> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderLineDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final cOrderLine entity = OBDal.getInstance().get(cOrderLine.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderLineDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
