// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.COrderlineServicerelationDTO;

/**
 * Etendo RX Endpoint: COrderlineServicerelationEndpoint
 *
 * Provides REST API for cOrderlineServicerelation entity with org-level filtering.
 */
@Path("/cOrderlineServicerelation")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class COrderlineServicerelationEndpoint {

  @GET
  public Response list(
    @QueryParam("mProductId") String mProductId
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<cOrderlineServicerelation> criteria = OBDal.getInstance()
          .createCriteria(cOrderlineServicerelation.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (mProductId != null) {
        criteria.add(Restrictions.eq("M_Product_ID", mProductId));
      }

      final List<cOrderlineServicerelation> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderlineServicerelationDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final cOrderlineServicerelation entity = OBDal.getInstance().get(cOrderlineServicerelation.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderlineServicerelationDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
