// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.COrderDTO;

/**
 * Etendo RX Endpoint: COrderEndpoint
 *
 * Provides REST API for cOrder entity with org-level filtering.
 */
@Path("/cOrder")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class COrderEndpoint {

  @GET
  public Response list(
    @QueryParam("adOrgId") String adOrgId,
    @QueryParam("cDocTypeTargetId") String cDocTypeTargetId,
    @QueryParam("documentNo") String documentNo,
    @QueryParam("cBpartnerId") String cBpartnerId,
    @QueryParam("cBpartnerLocationId") String cBpartnerLocationId,
    @QueryParam("mPriceListId") String mPriceListId,
    @QueryParam("finPaymentmethodId") String finPaymentmethodId,
    @QueryParam("cPaymentTermId") String cPaymentTermId,
    @QueryParam("mWarehouseId") String mWarehouseId,
    @QueryParam("cCurrencyId") String cCurrencyId,
    @QueryParam("adUserId") String adUserId,
    @QueryParam("poreference") String poreference,
    @QueryParam("salesRepId") String salesRepId,
    @QueryParam("billToId") String billToId,
    @QueryParam("deliveryLocationId") String deliveryLocationId,
    @QueryParam("mShipperId") String mShipperId,
    @QueryParam("cCampaignId") String cCampaignId,
    @QueryParam("cChargeId") String cChargeId,
    @QueryParam("cActivityId") String cActivityId,
    @QueryParam("adOrgTrxId") String adOrgTrxId,
    @QueryParam("quotationId") String quotationId,
    @QueryParam("cancelledorderId") String cancelledorderId,
    @QueryParam("replacedorderId") String replacedorderId,
    @QueryParam("bpartnerExtRef") String bpartnerExtRef,
    @QueryParam("cProjectId") String cProjectId,
    @QueryParam("cCostcenterId") String cCostcenterId,
    @QueryParam("aAssetId") String aAssetId,
    @QueryParam("user1Id") String user1Id,
    @QueryParam("user2Id") String user2Id,
    @QueryParam("dropShipLocationId") String dropShipLocationId,
    @QueryParam("dropShipBpartnerId") String dropShipBpartnerId,
    @QueryParam("dropShipUserId") String dropShipUserId,
    @QueryParam("cIncotermsId") String cIncotermsId
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<cOrder> criteria = OBDal.getInstance()
          .createCriteria(cOrder.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (adOrgId != null) {
        criteria.add(Restrictions.eq("AD_Org_ID", adOrgId));
      }
      if (cDocTypeTargetId != null) {
        criteria.add(Restrictions.eq("C_DocTypeTarget_ID", cDocTypeTargetId));
      }
      if (documentNo != null) {
        criteria.add(Restrictions.eq("DocumentNo", documentNo));
      }
      if (cBpartnerId != null) {
        criteria.add(Restrictions.eq("C_BPartner_ID", cBpartnerId));
      }
      if (cBpartnerLocationId != null) {
        criteria.add(Restrictions.eq("C_BPartner_Location_ID", cBpartnerLocationId));
      }
      if (mPriceListId != null) {
        criteria.add(Restrictions.eq("M_PriceList_ID", mPriceListId));
      }
      if (finPaymentmethodId != null) {
        criteria.add(Restrictions.eq("FIN_Paymentmethod_ID", finPaymentmethodId));
      }
      if (cPaymentTermId != null) {
        criteria.add(Restrictions.eq("C_PaymentTerm_ID", cPaymentTermId));
      }
      if (mWarehouseId != null) {
        criteria.add(Restrictions.eq("M_Warehouse_ID", mWarehouseId));
      }
      if (cCurrencyId != null) {
        criteria.add(Restrictions.eq("C_Currency_ID", cCurrencyId));
      }
      if (adUserId != null) {
        criteria.add(Restrictions.eq("AD_User_ID", adUserId));
      }
      if (poreference != null) {
        criteria.add(Restrictions.eq("POReference", poreference));
      }
      if (salesRepId != null) {
        criteria.add(Restrictions.eq("SalesRep_ID", salesRepId));
      }
      if (billToId != null) {
        criteria.add(Restrictions.eq("BillTo_ID", billToId));
      }
      if (deliveryLocationId != null) {
        criteria.add(Restrictions.eq("Delivery_Location_ID", deliveryLocationId));
      }
      if (mShipperId != null) {
        criteria.add(Restrictions.eq("M_Shipper_ID", mShipperId));
      }
      if (cCampaignId != null) {
        criteria.add(Restrictions.eq("C_Campaign_ID", cCampaignId));
      }
      if (cChargeId != null) {
        criteria.add(Restrictions.eq("C_Charge_ID", cChargeId));
      }
      if (cActivityId != null) {
        criteria.add(Restrictions.eq("C_Activity_ID", cActivityId));
      }
      if (adOrgTrxId != null) {
        criteria.add(Restrictions.eq("AD_OrgTrx_ID", adOrgTrxId));
      }
      if (quotationId != null) {
        criteria.add(Restrictions.eq("Quotation_ID", quotationId));
      }
      if (cancelledorderId != null) {
        criteria.add(Restrictions.eq("Cancelledorder_id", cancelledorderId));
      }
      if (replacedorderId != null) {
        criteria.add(Restrictions.eq("Replacedorder_id", replacedorderId));
      }
      if (bpartnerExtRef != null) {
        criteria.add(Restrictions.eq("BPartner_ExtRef", bpartnerExtRef));
      }
      if (cProjectId != null) {
        criteria.add(Restrictions.eq("C_Project_ID", cProjectId));
      }
      if (cCostcenterId != null) {
        criteria.add(Restrictions.eq("C_Costcenter_ID", cCostcenterId));
      }
      if (aAssetId != null) {
        criteria.add(Restrictions.eq("A_Asset_ID", aAssetId));
      }
      if (user1Id != null) {
        criteria.add(Restrictions.eq("User1_ID", user1Id));
      }
      if (user2Id != null) {
        criteria.add(Restrictions.eq("User2_ID", user2Id));
      }
      if (dropShipLocationId != null) {
        criteria.add(Restrictions.eq("DropShip_Location_ID", dropShipLocationId));
      }
      if (dropShipBpartnerId != null) {
        criteria.add(Restrictions.eq("DropShip_BPartner_ID", dropShipBpartnerId));
      }
      if (dropShipUserId != null) {
        criteria.add(Restrictions.eq("DropShip_User_ID", dropShipUserId));
      }
      if (cIncotermsId != null) {
        criteria.add(Restrictions.eq("C_Incoterms_ID", cIncotermsId));
      }

      final List<cOrder> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final cOrder entity = OBDal.getInstance().get(cOrder.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
