// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.COrderlineProductrelationDTO;

/**
 * Etendo RX Endpoint: COrderlineProductrelationEndpoint
 *
 * Provides REST API for cOrderlineProductrelation entity with org-level filtering.
 */
@Path("/cOrderlineProductrelation")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class COrderlineProductrelationEndpoint {

  @GET
  public Response list(
    @QueryParam("documentNo") String documentNo,
    @QueryParam("product") String product
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<cOrderlineProductrelation> criteria = OBDal.getInstance()
          .createCriteria(cOrderlineProductrelation.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (documentNo != null) {
        criteria.add(Restrictions.eq("documentNo", documentNo));
      }
      if (product != null) {
        criteria.add(Restrictions.eq("product", product));
      }

      final List<cOrderlineProductrelation> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderlineProductrelationDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final cOrderlineProductrelation entity = OBDal.getInstance().get(cOrderlineProductrelation.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderlineProductrelationDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
