// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.COrderTaxDTO;

/**
 * Etendo RX Endpoint: COrderTaxEndpoint
 *
 * Provides REST API for cOrderTax entity with org-level filtering.
 */
@Path("/cOrderTax")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class COrderTaxEndpoint {

  @GET
  public Response list(
    @QueryParam("cTaxId") String cTaxId
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<cOrderTax> criteria = OBDal.getInstance()
          .createCriteria(cOrderTax.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (cTaxId != null) {
        criteria.add(Restrictions.eq("C_Tax_ID", cTaxId));
      }

      final List<cOrderTax> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderTaxDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final cOrderTax entity = OBDal.getInstance().get(cOrderTax.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via COrderTaxDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
