// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.FinPaymentSchedOrdVDTO;

/**
 * Etendo RX Endpoint: FinPaymentSchedOrdVEndpoint
 *
 * Provides REST API for finPaymentSchedOrdV entity with org-level filtering.
 */
@Path("/finPaymentSchedOrdV")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class FinPaymentSchedOrdVEndpoint {

  @GET
  public Response list(
    @QueryParam("finPaymentmethodId") String finPaymentmethodId,
    @QueryParam("cCurrencyId") String cCurrencyId
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<finPaymentSchedOrdV> criteria = OBDal.getInstance()
          .createCriteria(finPaymentSchedOrdV.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (finPaymentmethodId != null) {
        criteria.add(Restrictions.eq("FIN_Paymentmethod_ID", finPaymentmethodId));
      }
      if (cCurrencyId != null) {
        criteria.add(Restrictions.eq("C_Currency_ID", cCurrencyId));
      }

      final List<finPaymentSchedOrdV> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via FinPaymentSchedOrdVDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final finPaymentSchedOrdV entity = OBDal.getInstance().get(finPaymentSchedOrdV.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via FinPaymentSchedOrdVDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
