// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.FinPaymentDetailVDTO;

/**
 * Etendo RX Endpoint: FinPaymentDetailVEndpoint
 *
 * Provides REST API for finPaymentDetailV entity with org-level filtering.
 */
@Path("/finPaymentDetailV")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class FinPaymentDetailVEndpoint {

  @GET
  public Response list(
    @QueryParam("finPaymentId") String finPaymentId,
    @QueryParam("emAprmDisplayedPaymmethId") String emAprmDisplayedPaymmethId,
    @QueryParam("emAprmDisplayedAccId") String emAprmDisplayedAccId,
    @QueryParam("finaccTxnConvertRate") String finaccTxnConvertRate
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<finPaymentDetailV> criteria = OBDal.getInstance()
          .createCriteria(finPaymentDetailV.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (finPaymentId != null) {
        criteria.add(Restrictions.eq("FIN_Payment_ID", finPaymentId));
      }
      if (emAprmDisplayedPaymmethId != null) {
        criteria.add(Restrictions.eq("EM_APRM_Displayed_Paymmeth_ID", emAprmDisplayedPaymmethId));
      }
      if (emAprmDisplayedAccId != null) {
        criteria.add(Restrictions.eq("EM_APRM_Displayed_Acc_ID", emAprmDisplayedAccId));
      }
      if (finaccTxnConvertRate != null) {
        criteria.add(Restrictions.eq("Finacc_Txn_Convert_Rate", finaccTxnConvertRate));
      }

      final List<finPaymentDetailV> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via FinPaymentDetailVDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final finPaymentDetailV entity = OBDal.getInstance().get(finPaymentDetailV.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via FinPaymentDetailVDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
