// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.rest.handler;

import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.hibernate.criterion.Restrictions;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import com.etendoerp.go.dto.MSolReservedStockVDTO;

/**
 * Etendo RX Endpoint: MSolReservedStockVEndpoint
 *
 * Provides REST API for mSolReservedStockV entity with org-level filtering.
 */
@Path("/mSolReservedStockV")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class MSolReservedStockVEndpoint {

  @GET
  public Response list(
    @QueryParam("mReservationId") String mReservationId,
    @QueryParam("mLocatorId") String mLocatorId,
    @QueryParam("cOrderlineId") String cOrderlineId,
    @QueryParam("cBpartnerId") String cBpartnerId
  ) {
    OBContext.setAdminMode(false);
    try {
      final OBCriteria<mSolReservedStockV> criteria = OBDal.getInstance()
          .createCriteria(mSolReservedStockV.class);

      // RT-5: Organization-level security filter
      criteria.add(Restrictions.in("organization.id",
          (Object[]) OBContext.getOBContext().getReadableOrganizations()));

      if (mReservationId != null) {
        criteria.add(Restrictions.eq("M_Reservation_ID", mReservationId));
      }
      if (mLocatorId != null) {
        criteria.add(Restrictions.eq("M_Locator_ID", mLocatorId));
      }
      if (cOrderlineId != null) {
        criteria.add(Restrictions.eq("C_Orderline_ID", cOrderlineId));
      }
      if (cBpartnerId != null) {
        criteria.add(Restrictions.eq("C_BPartner_ID", cBpartnerId));
      }

      final List<mSolReservedStockV> results = criteria.list();

      // TODO(vertical-slice): implement entity-to-DTO mapping via MSolReservedStockVDTO

      return Response.ok(results).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @GET
  @Path("/{id}")
  public Response getById(@PathParam("id") String id) {
    OBContext.setAdminMode(false);
    try {
      final mSolReservedStockV entity = OBDal.getInstance().get(mSolReservedStockV.class, id);
      if (entity == null) {
        return Response.status(Response.Status.NOT_FOUND).build();
      }

      // TODO(vertical-slice): implement entity-to-DTO mapping via MSolReservedStockVDTO

      return Response.ok(entity).build();

    } finally {
      OBContext.restorePreviousMode();
    }
  }
}
