// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Data Transfer Object: COrderDiscountDTO
 *
 * Version 1 — generated from curated schema.
 */
public class COrderDiscountDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private Integer line;
  private String cDiscountId;
  private Boolean cascade;
  private Boolean isactive;

  public COrderDiscountDTO() {
    // Default constructor
  }

  public Integer getLine() {
    return this.line;
  }

  public void setLine(Integer line) {
    this.line = line;
  }

  public String getCDiscountId() {
    return this.cDiscountId;
  }

  public void setCDiscountId(String cDiscountId) {
    this.cDiscountId = cDiscountId;
  }

  public Boolean getCascade() {
    return this.cascade;
  }

  public void setCascade(Boolean cascade) {
    this.cascade = cascade;
  }

  public Boolean getIsactive() {
    return this.isactive;
  }

  public void setIsactive(Boolean isactive) {
    this.isactive = isactive;
  }

}
