// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Data Transfer Object: COrderlineProductrelationDTO
 *
 * Version 1 — generated from curated schema.
 */
public class COrderlineProductrelationDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private String documentNo;
  private Integer lineNo;
  private String product;
  private String attributeSetValue;

  public COrderlineProductrelationDTO() {
    // Default constructor
  }

  public String getDocumentNo() {
    return this.documentNo;
  }

  public void setDocumentNo(String documentNo) {
    this.documentNo = documentNo;
  }

  public Integer getLineNo() {
    return this.lineNo;
  }

  public void setLineNo(Integer lineNo) {
    this.lineNo = lineNo;
  }

  public String getProduct() {
    return this.product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public String getAttributeSetValue() {
    return this.attributeSetValue;
  }

  public void setAttributeSetValue(String attributeSetValue) {
    this.attributeSetValue = attributeSetValue;
  }

}
