// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Data Transfer Object: COrderLineTaxDTO
 *
 * Version 1 — generated from curated schema.
 */
public class COrderLineTaxDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private Integer line;
  private String cTaxId;
  private BigDecimal taxbaseamt;
  private BigDecimal taxamt;

  public COrderLineTaxDTO() {
    // Default constructor
  }

  public Integer getLine() {
    return this.line;
  }

  public void setLine(Integer line) {
    this.line = line;
  }

  public String getCTaxId() {
    return this.cTaxId;
  }

  public void setCTaxId(String cTaxId) {
    this.cTaxId = cTaxId;
  }

  public BigDecimal getTaxbaseamt() {
    return this.taxbaseamt;
  }

  public void setTaxbaseamt(BigDecimal taxbaseamt) {
    this.taxbaseamt = taxbaseamt;
  }

  public BigDecimal getTaxamt() {
    return this.taxamt;
  }

  public void setTaxamt(BigDecimal taxamt) {
    this.taxamt = taxamt;
  }

}
