// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Data Transfer Object: COrderLineDTO
 *
 * Version 1 — generated from curated schema.
 */
public class COrderLineDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private Integer line;
  private String mProductId;
  private String aumqty;
  private String cAum;
  private String qtyOrdered;
  private String cUomId;
  private String mAttributeSetInstanceId;
  private String priceActual;
  private String grossUnitPrice;
  private BigDecimal lineNetAmt;
  private BigDecimal lineGrossAmount;
  private String cTaxId;
  private String priceList;
  private String grossPriceList;
  private String discount;
  private String mWarehouseRuleId;
  private String description;
  private String replacedorderlineId;
  private String createReservation;
  private BigDecimal taxbaseamt;
  private String qtyInvoiced;
  private String qtyDelivered;
  private Date dateOrdered;
  private Date datePromised;
  private Boolean directShip;
  private BigDecimal freightAmt;
  private Boolean cancelpricead;
  private String mProductUomId;
  private String quantityOrder;
  private String priceStd;
  private String grosspricestd;
  private String quotationlineId;
  private String soResStatus;
  private String manageReservation;
  private Boolean printDescription;
  private Integer overdueReturnDays;
  private String cProjectId;
  private String cCostcenterId;
  private String aAssetId;
  private String user1Id;
  private String user2Id;
  private String explode;
  private String relateOrderline;

  public COrderLineDTO() {
    // Default constructor
  }

  public Integer getLine() {
    return this.line;
  }

  public void setLine(Integer line) {
    this.line = line;
  }

  public String getMProductId() {
    return this.mProductId;
  }

  public void setMProductId(String mProductId) {
    this.mProductId = mProductId;
  }

  public String getAumqty() {
    return this.aumqty;
  }

  public void setAumqty(String aumqty) {
    this.aumqty = aumqty;
  }

  public String getCAum() {
    return this.cAum;
  }

  public void setCAum(String cAum) {
    this.cAum = cAum;
  }

  public String getQtyOrdered() {
    return this.qtyOrdered;
  }

  public void setQtyOrdered(String qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
  }

  public String getCUomId() {
    return this.cUomId;
  }

  public void setCUomId(String cUomId) {
    this.cUomId = cUomId;
  }

  public String getMAttributeSetInstanceId() {
    return this.mAttributeSetInstanceId;
  }

  public void setMAttributeSetInstanceId(String mAttributeSetInstanceId) {
    this.mAttributeSetInstanceId = mAttributeSetInstanceId;
  }

  public String getPriceActual() {
    return this.priceActual;
  }

  public void setPriceActual(String priceActual) {
    this.priceActual = priceActual;
  }

  public String getGrossUnitPrice() {
    return this.grossUnitPrice;
  }

  public void setGrossUnitPrice(String grossUnitPrice) {
    this.grossUnitPrice = grossUnitPrice;
  }

  public BigDecimal getLineNetAmt() {
    return this.lineNetAmt;
  }

  public void setLineNetAmt(BigDecimal lineNetAmt) {
    this.lineNetAmt = lineNetAmt;
  }

  public BigDecimal getLineGrossAmount() {
    return this.lineGrossAmount;
  }

  public void setLineGrossAmount(BigDecimal lineGrossAmount) {
    this.lineGrossAmount = lineGrossAmount;
  }

  public String getCTaxId() {
    return this.cTaxId;
  }

  public void setCTaxId(String cTaxId) {
    this.cTaxId = cTaxId;
  }

  public String getPriceList() {
    return this.priceList;
  }

  public void setPriceList(String priceList) {
    this.priceList = priceList;
  }

  public String getGrossPriceList() {
    return this.grossPriceList;
  }

  public void setGrossPriceList(String grossPriceList) {
    this.grossPriceList = grossPriceList;
  }

  public String getDiscount() {
    return this.discount;
  }

  public void setDiscount(String discount) {
    this.discount = discount;
  }

  public String getMWarehouseRuleId() {
    return this.mWarehouseRuleId;
  }

  public void setMWarehouseRuleId(String mWarehouseRuleId) {
    this.mWarehouseRuleId = mWarehouseRuleId;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getReplacedorderlineId() {
    return this.replacedorderlineId;
  }

  public void setReplacedorderlineId(String replacedorderlineId) {
    this.replacedorderlineId = replacedorderlineId;
  }

  public String getCreateReservation() {
    return this.createReservation;
  }

  public void setCreateReservation(String createReservation) {
    this.createReservation = createReservation;
  }

  public BigDecimal getTaxbaseamt() {
    return this.taxbaseamt;
  }

  public void setTaxbaseamt(BigDecimal taxbaseamt) {
    this.taxbaseamt = taxbaseamt;
  }

  public String getQtyInvoiced() {
    return this.qtyInvoiced;
  }

  public void setQtyInvoiced(String qtyInvoiced) {
    this.qtyInvoiced = qtyInvoiced;
  }

  public String getQtyDelivered() {
    return this.qtyDelivered;
  }

  public void setQtyDelivered(String qtyDelivered) {
    this.qtyDelivered = qtyDelivered;
  }

  public Date getDateOrdered() {
    return this.dateOrdered;
  }

  public void setDateOrdered(Date dateOrdered) {
    this.dateOrdered = dateOrdered;
  }

  public Date getDatePromised() {
    return this.datePromised;
  }

  public void setDatePromised(Date datePromised) {
    this.datePromised = datePromised;
  }

  public Boolean getDirectShip() {
    return this.directShip;
  }

  public void setDirectShip(Boolean directShip) {
    this.directShip = directShip;
  }

  public BigDecimal getFreightAmt() {
    return this.freightAmt;
  }

  public void setFreightAmt(BigDecimal freightAmt) {
    this.freightAmt = freightAmt;
  }

  public Boolean getCancelpricead() {
    return this.cancelpricead;
  }

  public void setCancelpricead(Boolean cancelpricead) {
    this.cancelpricead = cancelpricead;
  }

  public String getMProductUomId() {
    return this.mProductUomId;
  }

  public void setMProductUomId(String mProductUomId) {
    this.mProductUomId = mProductUomId;
  }

  public String getQuantityOrder() {
    return this.quantityOrder;
  }

  public void setQuantityOrder(String quantityOrder) {
    this.quantityOrder = quantityOrder;
  }

  public String getPriceStd() {
    return this.priceStd;
  }

  public void setPriceStd(String priceStd) {
    this.priceStd = priceStd;
  }

  public String getGrosspricestd() {
    return this.grosspricestd;
  }

  public void setGrosspricestd(String grosspricestd) {
    this.grosspricestd = grosspricestd;
  }

  public String getQuotationlineId() {
    return this.quotationlineId;
  }

  public void setQuotationlineId(String quotationlineId) {
    this.quotationlineId = quotationlineId;
  }

  public String getSoResStatus() {
    return this.soResStatus;
  }

  public void setSoResStatus(String soResStatus) {
    this.soResStatus = soResStatus;
  }

  public String getManageReservation() {
    return this.manageReservation;
  }

  public void setManageReservation(String manageReservation) {
    this.manageReservation = manageReservation;
  }

  public Boolean getPrintDescription() {
    return this.printDescription;
  }

  public void setPrintDescription(Boolean printDescription) {
    this.printDescription = printDescription;
  }

  public Integer getOverdueReturnDays() {
    return this.overdueReturnDays;
  }

  public void setOverdueReturnDays(Integer overdueReturnDays) {
    this.overdueReturnDays = overdueReturnDays;
  }

  public String getCProjectId() {
    return this.cProjectId;
  }

  public void setCProjectId(String cProjectId) {
    this.cProjectId = cProjectId;
  }

  public String getCCostcenterId() {
    return this.cCostcenterId;
  }

  public void setCCostcenterId(String cCostcenterId) {
    this.cCostcenterId = cCostcenterId;
  }

  public String getAAssetId() {
    return this.aAssetId;
  }

  public void setAAssetId(String aAssetId) {
    this.aAssetId = aAssetId;
  }

  public String getUser1Id() {
    return this.user1Id;
  }

  public void setUser1Id(String user1Id) {
    this.user1Id = user1Id;
  }

  public String getUser2Id() {
    return this.user2Id;
  }

  public void setUser2Id(String user2Id) {
    this.user2Id = user2Id;
  }

  public String getExplode() {
    return this.explode;
  }

  public void setExplode(String explode) {
    this.explode = explode;
  }

  public String getRelateOrderline() {
    return this.relateOrderline;
  }

  public void setRelateOrderline(String relateOrderline) {
    this.relateOrderline = relateOrderline;
  }

}
