// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Data Transfer Object: COrderTaxDTO
 *
 * Version 1 — generated from curated schema.
 */
public class COrderTaxDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private Integer line;
  private String cTaxId;
  private BigDecimal taxAmt;
  private BigDecimal taxBaseAmt;

  public COrderTaxDTO() {
    // Default constructor
  }

  public Integer getLine() {
    return this.line;
  }

  public void setLine(Integer line) {
    this.line = line;
  }

  public String getCTaxId() {
    return this.cTaxId;
  }

  public void setCTaxId(String cTaxId) {
    this.cTaxId = cTaxId;
  }

  public BigDecimal getTaxAmt() {
    return this.taxAmt;
  }

  public void setTaxAmt(BigDecimal taxAmt) {
    this.taxAmt = taxAmt;
  }

  public BigDecimal getTaxBaseAmt() {
    return this.taxBaseAmt;
  }

  public void setTaxBaseAmt(BigDecimal taxBaseAmt) {
    this.taxBaseAmt = taxBaseAmt;
  }

}
