// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Data Transfer Object: MSolReservedStockVDTO
 *
 * Version 1 — generated from curated schema.
 */
public class MSolReservedStockVDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private String mReservationId;
  private String mLocatorId;
  private String mAttributesetinstanceId;
  private String cOrderlineId;
  private String cBpartnerId;
  private String quantity;
  private String releasedQty;

  public MSolReservedStockVDTO() {
    // Default constructor
  }

  public String getMReservationId() {
    return this.mReservationId;
  }

  public void setMReservationId(String mReservationId) {
    this.mReservationId = mReservationId;
  }

  public String getMLocatorId() {
    return this.mLocatorId;
  }

  public void setMLocatorId(String mLocatorId) {
    this.mLocatorId = mLocatorId;
  }

  public String getMAttributesetinstanceId() {
    return this.mAttributesetinstanceId;
  }

  public void setMAttributesetinstanceId(String mAttributesetinstanceId) {
    this.mAttributesetinstanceId = mAttributesetinstanceId;
  }

  public String getCOrderlineId() {
    return this.cOrderlineId;
  }

  public void setCOrderlineId(String cOrderlineId) {
    this.cOrderlineId = cOrderlineId;
  }

  public String getCBpartnerId() {
    return this.cBpartnerId;
  }

  public void setCBpartnerId(String cBpartnerId) {
    this.cBpartnerId = cBpartnerId;
  }

  public String getQuantity() {
    return this.quantity;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }

  public String getReleasedQty() {
    return this.releasedQty;
  }

  public void setReleasedQty(String releasedQty) {
    this.releasedQty = releasedQty;
  }

}
