/*
 * *************************************************************************
 * The contents of this file are subject to the Etendo License
 * (the "License"), you may not use this file except in compliance with
 * the License.
 * You may obtain a copy of the License at
 * https://github.com/etendosoftware/etendo_core/blob/main/legal/Etendo_license.txt
 * Software distributed under the License is distributed on an
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing rights
 * and limitations under the License.
 * All portions are Copyright (C) 2021-2026 FUTIT SERVICES, S.L
 * All Rights Reserved.
 * Contributor(s): Futit Services S.L.
 * *************************************************************************
 */
package com.etendoerp.go.onboarding;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Pattern;

import javax.xml.parsers.DocumentBuilderFactory;

import org.junit.Test;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 * ETP-5426 — {@link OnboardingSampleDataDefinition}: eligibility, value rewrites, and the
 * guarantee that the sample data only references rows a tenant will actually have.
 */
public class OnboardingSampleDataDefinitionTest {

  private static final Pattern ETENDO_ID = Pattern.compile("[0-9A-F]{32}");
  private static final String ID_SUFFIX = "_ID";
  /** Remapped to the tenant by the normalizer itself, never resolved as references. */
  private static final Set<String> OWNERSHIP_COLUMNS = Set.of("AD_CLIENT_ID", "AD_ORG_ID");

  @Test
  public void testOnlyADemoSpanishEuroSignupThatOptedInIsEligible() {
    assertTrue(OnboardingSampleDataService.isEligible(true, false, "ES", "EUR"));
    assertTrue("codes are compared case-insensitively",
        OnboardingSampleDataService.isEligible(true, false, "es", "eur"));

    assertFalse("opt-in is required", OnboardingSampleDataService.isEligible(false, false, "ES", "EUR"));
    assertFalse("a paid environment never gets sample data",
        OnboardingSampleDataService.isEligible(true, true, "ES", "EUR"));
    assertFalse("Spanish data only", OnboardingSampleDataService.isEligible(true, false, "AR", "EUR"));
    assertFalse("EUR data only", OnboardingSampleDataService.isEligible(true, false, "ES", "USD"));
    assertFalse(OnboardingSampleDataService.isEligible(true, false, null, null));
  }

  @Test
  public void testPostedIsRewrittenToUnpostedExceptWhenPostingIsDisabled() {
    assertEquals("N", OnboardingSampleDataDefinition.rewriteValue("POSTED", "Y"));
    assertEquals("N", OnboardingSampleDataDefinition.rewriteValue("POSTED", "T"));
    assertEquals("N", OnboardingSampleDataDefinition.rewriteValue("POSTED", "N"));
    assertEquals("D", OnboardingSampleDataDefinition.rewriteValue("POSTED", "D"));
    assertEquals("other columns are untouched", "Y",
        OnboardingSampleDataDefinition.rewriteValue("PROCESSED", "Y"));
  }

  @Test
  public void testUserReferencesAreStrippedOnlyWhereTheyPointAtGoClientUsers() {
    for (String table : new String[] { "C_ORDER", "C_INVOICE", "M_INOUT", "A_ASSET", "C_Order" }) {
      assertTrue(table, OnboardingSampleDataDefinition.isStrippedColumn(table, "AD_USER_ID"));
    }
    assertFalse(OnboardingSampleDataDefinition.isStrippedColumn("C_BPARTNER", "AD_USER_ID"));
    assertFalse(OnboardingSampleDataDefinition.isStrippedColumn("C_ORDER", "C_BPARTNER_ID"));
    assertFalse(OnboardingSampleDataDefinition.isStrippedColumn(null, "AD_USER_ID"));
  }

  @Test
  public void testOnlyPartnersWithoutIdentifierGetThePendingStandIn() {
    assertEquals(Map.of("EM_ETGO_IDENTIFIER", OnboardingSampleDataDefinition.PENDING_IDENTIFIER),
        OnboardingSampleDataDefinition.addedColumns("C_BPartner", Map.of("VALUE", "Juan Perez")));
    assertEquals(Map.of("EM_ETGO_IDENTIFIER", OnboardingSampleDataDefinition.PENDING_IDENTIFIER),
        OnboardingSampleDataDefinition.addedColumns("C_BPARTNER", Map.of("EM_ETGO_IDENTIFIER", " ")));
    assertEquals(Map.of(), OnboardingSampleDataDefinition.addedColumns("C_BPARTNER",
        Map.of("EM_ETGO_IDENTIFIER", "Español")));
    assertEquals(Map.of(), OnboardingSampleDataDefinition.addedColumns("C_ORDER", Map.of()));
    assertTrue("the stand-in must fit C_BPartner.EM_Etgo_Identifier (32)",
        OnboardingSampleDataDefinition.PENDING_IDENTIFIER.length() <= 32);
    assertFalse("a value starting with '<' is regenerated by the sequence generator",
        OnboardingSampleDataDefinition.PENDING_IDENTIFIER.startsWith("<"));
  }

  @Test
  public void testTheSampleDataNeverOverlapsTheBaseDatasetExceptForTheDemoMasterData() {
    for (String table : OnboardingSampleDataDefinition.TRANSACTIONAL_TABLES) {
      assertFalse(table + " is sample data; the base pass must not import it",
          OnboardingDatasetDefinition.shouldIncludeTable(table));
    }
    for (String table : OnboardingSampleDataDefinition.DEMO_MASTER_DATA_TABLES) {
      assertTrue(table + " is shared with the base pass, which imports its non-demo rows",
          OnboardingDatasetDefinition.shouldIncludeTable(table));
    }
    assertFalse("the sample data is imported unposted",
        OnboardingSampleDataDefinition.includesTable("FACT_ACCT"));
  }

  /** The "already imported" markers must be GOClient partners the sample pass actually imports. */
  @Test
  public void testPresenceMarkersAreTheBundledBusinessPartners() throws Exception {
    Set<String> partnerIds = definedIds("C_BPARTNER");
    assertEquals(partnerIds, OnboardingSampleDataDefinition.PRESENCE_MARKER_BUSINESS_PARTNER_IDS);
  }

  /**
   * Every reference from a sample-data row to a table the dataset ships must land on a table a
   * tenant receives — through the base pass or through this one — unless the column is stripped.
   *
   * <p>This is the sample-data counterpart of
   * {@link OnboardingDatasetReferentialIntegrityTest#testEveryReferenceToADatasetOwnedTableResolves()}:
   * that test guarantees the SOURCE is complete for {@code install.source}; this one guarantees the
   * sample pass does not reference a table no pass imports, which {@code DataImportService} would
   * refuse with "not present in the xml or in the database" and turn into a sample-data warning on
   * every signup.
   */
  @Test
  public void testSampleDataOnlyReferencesTablesATenantReceives() throws Exception {
    Set<String> datasetTables = new HashSet<>();
    try (var files = Files.list(sampleDataDirectory())) {
      files.map(path -> path.getFileName().toString())
          .filter(name -> name.endsWith(".xml"))
          .forEach(name -> datasetTables.add(name.substring(0, name.length() - 4).toUpperCase()));
    }

    Set<String> unreachable = new TreeSet<>();
    for (String sourceTable : OnboardingSampleDataDefinition.TRANSACTIONAL_TABLES) {
      for (Element row : rows(sourceTable)) {
        NodeList columns = row.getChildNodes();
        for (int i = 0; i < columns.getLength(); i++) {
          Node column = columns.item(i);
          if (!(column instanceof Element)) {
            continue;
          }
          String columnName = column.getNodeName().toUpperCase();
          String value = column.getTextContent() == null ? "" : column.getTextContent().trim();
          if (!columnName.endsWith(ID_SUFFIX) || !ETENDO_ID.matcher(value).matches()
              || OWNERSHIP_COLUMNS.contains(columnName)
              || OnboardingDatasetProfile.SAMPLE_DATA.isStrippedColumn(sourceTable, columnName)) {
            continue;
          }
          String target = columnName.substring(0, columnName.length() - ID_SUFFIX.length());
          if (target.equals(sourceTable) || !datasetTables.contains(target)) {
            continue;
          }
          if (!OnboardingSampleDataDefinition.includesTable(target)
              && !OnboardingDatasetDefinition.shouldIncludeTable(target)) {
            unreachable.add(sourceTable + "." + columnName + " -> " + target);
          }
        }
      }
    }
    if (!unreachable.isEmpty()) {
      fail("sample-data rows reference tables no onboarding pass imports: " + unreachable);
    }
  }

  // ── internals ──────────────────────────────────────────────────────────────

  private Set<String> definedIds(String table) throws Exception {
    Set<String> ids = new HashSet<>();
    for (Element row : rows(table)) {
      NodeList columns = row.getElementsByTagName(table + ID_SUFFIX);
      if (columns.getLength() > 0) {
        ids.add(columns.item(0).getTextContent().trim());
      }
    }
    return ids;
  }

  private List<Element> rows(String table) throws Exception {
    Path file = sampleDataDirectory().resolve(table + ".xml");
    var document = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(file.toFile());
    NodeList children = document.getDocumentElement().getChildNodes();
    List<Element> rows = new ArrayList<>();
    for (int i = 0; i < children.getLength(); i++) {
      Node child = children.item(i);
      if (child instanceof Element && table.equalsIgnoreCase(child.getNodeName())) {
        rows.add((Element) child);
      }
    }
    return rows;
  }

  private Path sampleDataDirectory() {
    Path moduleRelative = Paths.get("referencedata", "sampledata", "GOClient");
    if (Files.isDirectory(moduleRelative)) {
      return moduleRelative;
    }
    Path rootRelative = Paths.get("modules", "com.etendoerp.go", "referencedata", "sampledata",
        "GOClient");
    if (Files.isDirectory(rootRelative)) {
      return rootRelative;
    }
    throw new IllegalStateException("GOClient sampledata directory not found");
  }
}
