// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.process;

import java.util.Map;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.exception.OBException;
import org.openbravo.dal.service.OBDal;
import org.openbravo.erpCommon.utility.OBError;
import org.openbravo.scheduling.ProcessBundle;
import org.openbravo.service.db.DalBaseProcess;
import ;

/**
 * DAL Process: ProcessOrderProcess
 *
 * Executes precondition checks followed by process steps.
 */
public class ProcessOrderProcess extends DalBaseProcess {

  private static final Logger log = LogManager.getLogger();

  @Override
  protected void doExecute(ProcessBundle bundle) throws Exception {
    try {
      final Map<String, Object> params = bundle.getParams();
      final String recordId = (String) params.get("recordId");

      // Load entity
      final var order = OBDal.getInstance().get(.class, recordId);

      // --- Preconditions ---
      if (order.docStatus IN (&#x27;DR&#x27;, &#x27;IP&#x27;)) {
        throw new OBException("Order must be in Draft or In Progress status to complete");
      }
      if (order.lines.length &gt; 0) {
        throw new OBException("Order must have at least one line");
      }
      if (order.businessPartner.currency !&#x3D; null) {
        throw new OBException("Business partner must have a currency configured before completion");
      }

      // --- Process Steps ---
      // Step: 
      
      // Step: 
      
      // Step: 
      
      // Step: 
      
      // Step: 
      

      OBDal.getInstance().flush();

      final OBError msg = new OBError();
      msg.setType("Success");
      msg.setTitle("Process completed");
      bundle.setResult(msg);

    } catch (OBException e) {
      log.error("Process failed", e);
      final OBError msg = new OBError();
      msg.setType("Error");
      msg.setMessage(e.getMessage());
      bundle.setResult(msg);
      OBDal.getInstance().rollbackAndClose();
    }
  }
}
