// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.event;

import javax.enterprise.event.Observes;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;

/**
 * Event handler for cOrderlineServicerelation entity derivations.
 *
 * Table: C_Orderline_Servicerelation
 * Derivations: 9
 */
public class COrderlineServicerelationDerivationHandler extends EntityPersistenceEventObserver {

  private static final Logger log = LogManager.getLogger();
  private static final String TABLE_NAME = "C_Orderline_Servicerelation";

  private Entity[] entities = {
    ModelProvider.getInstance().getEntityByTableName(TABLE_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return entities;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(EntityPersistenceEvent event) {
    // Derivation: adOrgId → column AD_Org_ID (type: fromConfig, source: context.organization)
    // TODO(vertical-slice): implement fromConfig derivation for adOrgId
    // Derivation: isactive → column Isactive (type: computed, source: Y)
    // TODO(vertical-slice): implement computed derivation for isactive
    // Derivation: cOrderlineId → column C_Orderline_ID (type: fromParent, source: cOrderLine.cOrderLineId)
    // TODO(vertical-slice): implement fromParent derivation for cOrderlineId
    // Derivation: cOrderlineRelatedId → column C_Orderline_Related_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for cOrderlineRelatedId
    // Derivation: documentNo → column DocumentNo (type: sequence, source: documentType.sequence)
    // TODO(vertical-slice): implement sequence derivation for documentNo
    // Derivation: amount → column Amount (type: computed, source: 0)
    // TODO(vertical-slice): implement computed derivation for amount
    // Derivation: quantity → column Quantity (type: computed, source: 0)
    // TODO(vertical-slice): implement computed derivation for quantity
    // Derivation: adClientId → column AD_Client_ID (type: fromConfig, source: context.client)
    // TODO(vertical-slice): implement fromConfig derivation for adClientId
    // Derivation: cOrderlineServicerelationId → column C_Orderline_Servicerelation_ID (type: sequence, source: )
    // TODO(vertical-slice): implement sequence derivation for cOrderlineServicerelationId
  }
}
