// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.event;

import javax.enterprise.event.Observes;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;

/**
 * Event handler for cOrder entity derivations.
 *
 * Table: C_Order
 * Derivations: 14
 */
public class COrderDerivationHandler extends EntityPersistenceEventObserver {

  private static final Logger log = LogManager.getLogger();
  private static final String TABLE_NAME = "C_Order";

  private Entity[] entities = {
    ModelProvider.getInstance().getEntityByTableName(TABLE_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return entities;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(EntityPersistenceEvent event) {
    // Derivation: cDocTypeId → column C_DocType_ID (type: fromConfig, source: doctype.salesOrder)
    // TODO(vertical-slice): implement fromConfig derivation for cDocTypeId
    // Derivation: replacementorderId → column Replacementorder_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for replacementorderId
    // Derivation: isSelfService → column IsSelfService (type: computed, source: false)
    // TODO(vertical-slice): implement computed derivation for isSelfService
    // Derivation: isSelected → column IsSelected (type: computed, source: false)
    // TODO(vertical-slice): implement computed derivation for isSelected
    // Derivation: posted → column Posted (type: computed, source: 'N')
    // TODO(vertical-slice): implement computed derivation for posted
    // Derivation: isSotrx → column IsSOTrx (type: fromConfig, source: context.isSotrx)
    // TODO(vertical-slice): implement fromConfig derivation for isSotrx
    // Derivation: datePrinted → column DatePrinted (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for datePrinted
    // Derivation: processed → column Processed (type: computed, source: false)
    // TODO(vertical-slice): implement computed derivation for processed
    // Derivation: processing → column Processing (type: computed, source: false)
    // TODO(vertical-slice): implement computed derivation for processing
    // Derivation: cOrderId → column C_Order_ID (type: sequence, source: )
    // TODO(vertical-slice): implement sequence derivation for cOrderId
    // Derivation: isPrinted → column IsPrinted (type: computed, source: false)
    // TODO(vertical-slice): implement computed derivation for isPrinted
    // Derivation: isInvoiced → column IsInvoiced (type: computed, source: false)
    // TODO(vertical-slice): implement computed derivation for isInvoiced
    // Derivation: isActive → column IsActive (type: computed, source: true)
    // TODO(vertical-slice): implement computed derivation for isActive
    // Derivation: adClientId → column AD_Client_ID (type: fromConfig, source: context.client)
    // TODO(vertical-slice): implement fromConfig derivation for adClientId
  }
}
