// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.event;

import javax.enterprise.event.Observes;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;

/**
 * Event handler for cOrderLine entity derivations.
 *
 * Table: C_OrderLine
 * Derivations: 20
 */
public class COrderLineDerivationHandler extends EntityPersistenceEventObserver {

  private static final Logger log = LogManager.getLogger();
  private static final String TABLE_NAME = "C_OrderLine";

  private Entity[] entities = {
    ModelProvider.getInstance().getEntityByTableName(TABLE_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return entities;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(EntityPersistenceEvent event) {
    // Derivation: mWarehouseId → column M_Warehouse_ID (type: fromConfig, source: context.mWarehouseId)
    // TODO(vertical-slice): implement fromConfig derivation for mWarehouseId
    // Derivation: qtyReserved → column QtyReserved (type: computed, source: 0)
    // TODO(vertical-slice): implement computed derivation for qtyReserved
    // Derivation: mShipperId → column M_Shipper_ID (type: fromConfig, source: context.mShipperId)
    // TODO(vertical-slice): implement fromConfig derivation for mShipperId
    // Derivation: cBpartnerId → column C_BPartner_ID (type: lookup, source: SELECT C_BPartner_ID AS DefaultValue FROM C_Order WHERE C_Order_ID=@C_Order_ID@)
    // TODO(vertical-slice): implement lookup derivation for cBpartnerId
    // Derivation: cBpartnerLocationId → column C_BPartner_Location_ID (type: fromConfig, source: context.cBpartnerLocationId)
    // TODO(vertical-slice): implement fromConfig derivation for cBpartnerLocationId
    // Derivation: iseditlinenetamt → column Iseditlinenetamt (type: computed, source: N)
    // TODO(vertical-slice): implement computed derivation for iseditlinenetamt
    // Derivation: adOrgId → column AD_Org_ID (type: fromConfig, source: context.organization)
    // TODO(vertical-slice): implement fromConfig derivation for adOrgId
    // Derivation: bomParentId → column BOM_Parent_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for bomParentId
    // Derivation: cOrderDiscountId → column C_Order_Discount_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for cOrderDiscountId
    // Derivation: mOfferId → column M_Offer_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for mOfferId
    // Derivation: isDescription → column IsDescription (type: computed, source: N)
    // TODO(vertical-slice): implement computed derivation for isDescription
    // Derivation: sResourceAssignmentId → column S_ResourceAssignment_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for sResourceAssignmentId
    // Derivation: priceLimit → column PriceLimit (type: computed, source: 0)
    // TODO(vertical-slice): implement computed derivation for priceLimit
    // Derivation: cCurrencyId → column C_Currency_ID (type: fromConfig, source: context.cCurrencyId)
    // TODO(vertical-slice): implement fromConfig derivation for cCurrencyId
    // Derivation: dateInvoiced → column DateInvoiced (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for dateInvoiced
    // Derivation: dateDelivered → column DateDelivered (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for dateDelivered
    // Derivation: cOrderId → column C_Order_ID (type: fromParent, source: cOrder.cOrderId)
    // TODO(vertical-slice): implement fromParent derivation for cOrderId
    // Derivation: isActive → column IsActive (type: computed, source: true)
    // TODO(vertical-slice): implement computed derivation for isActive
    // Derivation: adClientId → column AD_Client_ID (type: fromConfig, source: context.client)
    // TODO(vertical-slice): implement fromConfig derivation for adClientId
    // Derivation: cOrderLineId → column C_OrderLine_ID (type: sequence, source: )
    // TODO(vertical-slice): implement sequence derivation for cOrderLineId
  }
}
