// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.event;

import javax.enterprise.event.Observes;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;

/**
 * Event handler for cOrderlineProductrelation entity derivations.
 *
 * Table: C_Orderline_Productrelation
 * Derivations: 2
 */
public class COrderlineProductrelationDerivationHandler extends EntityPersistenceEventObserver {

  private static final Logger log = LogManager.getLogger();
  private static final String TABLE_NAME = "C_Orderline_Productrelation";

  private Entity[] entities = {
    ModelProvider.getInstance().getEntityByTableName(TABLE_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return entities;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(EntityPersistenceEvent event) {
    // Derivation: amount → column amount (type: computed, source: 0)
    // TODO(vertical-slice): implement computed derivation for amount
    // Derivation: quantity → column quantity (type: computed, source: 0)
    // TODO(vertical-slice): implement computed derivation for quantity
  }
}
