// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.event;

import javax.enterprise.event.Observes;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;

/**
 * Event handler for finPaymentDetailV entity derivations.
 *
 * Table: FIN_Payment_Detail_V
 * Derivations: 14
 */
public class FinPaymentDetailVDerivationHandler extends EntityPersistenceEventObserver {

  private static final Logger log = LogManager.getLogger();
  private static final String TABLE_NAME = "FIN_Payment_Detail_V";

  private Entity[] entities = {
    ModelProvider.getInstance().getEntityByTableName(TABLE_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return entities;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(EntityPersistenceEvent event) {
    // Derivation: finPaymentmethodId → column Fin_Paymentmethod_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for finPaymentmethodId
    // Derivation: finFinancialAccountId → column Fin_Financial_Account_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for finFinancialAccountId
    // Derivation: cCurrencyId → column C_Currency_ID (type: fromParent, source: finPaymentSchedOrdV.cCurrencyId)
    // TODO(vertical-slice): implement fromParent derivation for cCurrencyId
    // Derivation: paymentno → column Paymentno (type: computed, source: '')
    // TODO(vertical-slice): implement computed derivation for paymentno
    // Derivation: finaccCurrencyId → column Finacc_Currency_ID (type: computed, source: null)
    // TODO(vertical-slice): implement computed derivation for finaccCurrencyId
    // Derivation: finPaymentSchedOrdVId → column Fin_Payment_Sched_Ord_V_Id (type: fromParent, source: finPaymentSchedOrdV.finPaymentSchedOrdVId)
    // TODO(vertical-slice): implement fromParent derivation for finPaymentSchedOrdVId
    // Derivation: isactive → column Isactive (type: computed, source: true)
    // TODO(vertical-slice): implement computed derivation for isactive
    // Derivation: orderno → column Orderno (type: computed, source: '')
    // TODO(vertical-slice): implement computed derivation for orderno
    // Derivation: adOrgId → column AD_Org_ID (type: fromConfig, source: context.organization)
    // TODO(vertical-slice): implement fromConfig derivation for adOrgId
    // Derivation: finPaymentDetailVId → column Fin_Payment_Detail_V_ID (type: sequence, source: )
    // TODO(vertical-slice): implement sequence derivation for finPaymentDetailVId
    // Derivation: invoiceno → column Invoiceno (type: computed, source: '')
    // TODO(vertical-slice): implement computed derivation for invoiceno
    // Derivation: invoicedamt → column Invoicedamt (type: computed, source: 0)
    // TODO(vertical-slice): implement computed derivation for invoicedamt
    // Derivation: cBpartnerId → column C_Bpartner_ID (type: fromParent, source: cOrder.cBpartnerId)
    // TODO(vertical-slice): implement fromParent derivation for cBpartnerId
    // Derivation: adClientId → column AD_Client_ID (type: fromConfig, source: context.client)
    // TODO(vertical-slice): implement fromConfig derivation for adClientId
  }
}
