// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.handler;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import org.openbravo.model.common.order.Order;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: COrderHandler
 *
 * Entity: cOrder (C_Order)
 * OBDal class: Order
 */
public class COrderHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";

  @Override
  public String getBasePath() {
    return "/cOrder";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement create for Order
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"POST not yet implemented for cOrder\"}");
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement update for Order
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for cOrder\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement delete for Order
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for cOrder\"}");
  }

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    OBCriteria<Order> criteria = OBDal.getInstance().createCriteria(Order.class);
    criteria.setMaxResults(100);

    // Filter: adOrgId (String) → column AD_Org_ID
    String paramadOrgId = request.getParameter("adOrgId");
    if (paramadOrgId != null && !paramadOrgId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("adOrgId", paramadOrgId));
    }
    // Filter: cDocTypeTargetId (String) → column C_DocTypeTarget_ID
    String paramcDocTypeTargetId = request.getParameter("cDocTypeTargetId");
    if (paramcDocTypeTargetId != null && !paramcDocTypeTargetId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cDocTypeTargetId", paramcDocTypeTargetId));
    }
    // Filter: documentNo (String) → column DocumentNo
    String paramdocumentNo = request.getParameter("documentNo");
    if (paramdocumentNo != null && !paramdocumentNo.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("documentNo", paramdocumentNo));
    }
    // Filter: cBpartnerId (String) → column C_BPartner_ID
    String paramcBpartnerId = request.getParameter("cBpartnerId");
    if (paramcBpartnerId != null && !paramcBpartnerId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cBpartnerId", paramcBpartnerId));
    }
    // Filter: cBpartnerLocationId (String) → column C_BPartner_Location_ID
    String paramcBpartnerLocationId = request.getParameter("cBpartnerLocationId");
    if (paramcBpartnerLocationId != null && !paramcBpartnerLocationId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cBpartnerLocationId", paramcBpartnerLocationId));
    }
    // Filter: mPriceListId (String) → column M_PriceList_ID
    String parammPriceListId = request.getParameter("mPriceListId");
    if (parammPriceListId != null && !parammPriceListId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mPriceListId", parammPriceListId));
    }
    // Filter: finPaymentmethodId (String) → column FIN_Paymentmethod_ID
    String paramfinPaymentmethodId = request.getParameter("finPaymentmethodId");
    if (paramfinPaymentmethodId != null && !paramfinPaymentmethodId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("finPaymentmethodId", paramfinPaymentmethodId));
    }
    // Filter: cPaymentTermId (String) → column C_PaymentTerm_ID
    String paramcPaymentTermId = request.getParameter("cPaymentTermId");
    if (paramcPaymentTermId != null && !paramcPaymentTermId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cPaymentTermId", paramcPaymentTermId));
    }
    // Filter: mWarehouseId (String) → column M_Warehouse_ID
    String parammWarehouseId = request.getParameter("mWarehouseId");
    if (parammWarehouseId != null && !parammWarehouseId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mWarehouseId", parammWarehouseId));
    }
    // Filter: cCurrencyId (String) → column C_Currency_ID
    String paramcCurrencyId = request.getParameter("cCurrencyId");
    if (paramcCurrencyId != null && !paramcCurrencyId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cCurrencyId", paramcCurrencyId));
    }
    // Filter: adUserId (String) → column AD_User_ID
    String paramadUserId = request.getParameter("adUserId");
    if (paramadUserId != null && !paramadUserId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("adUserId", paramadUserId));
    }
    // Filter: poreference (String) → column POReference
    String paramporeference = request.getParameter("poreference");
    if (paramporeference != null && !paramporeference.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("poreference", paramporeference));
    }
    // Filter: salesRepId (String) → column SalesRep_ID
    String paramsalesRepId = request.getParameter("salesRepId");
    if (paramsalesRepId != null && !paramsalesRepId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("salesRepId", paramsalesRepId));
    }
    // Filter: billToId (String) → column BillTo_ID
    String parambillToId = request.getParameter("billToId");
    if (parambillToId != null && !parambillToId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("billToId", parambillToId));
    }
    // Filter: deliveryLocationId (String) → column Delivery_Location_ID
    String paramdeliveryLocationId = request.getParameter("deliveryLocationId");
    if (paramdeliveryLocationId != null && !paramdeliveryLocationId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("deliveryLocationId", paramdeliveryLocationId));
    }
    // Filter: mShipperId (String) → column M_Shipper_ID
    String parammShipperId = request.getParameter("mShipperId");
    if (parammShipperId != null && !parammShipperId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mShipperId", parammShipperId));
    }
    // Filter: cCampaignId (String) → column C_Campaign_ID
    String paramcCampaignId = request.getParameter("cCampaignId");
    if (paramcCampaignId != null && !paramcCampaignId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cCampaignId", paramcCampaignId));
    }
    // Filter: cChargeId (String) → column C_Charge_ID
    String paramcChargeId = request.getParameter("cChargeId");
    if (paramcChargeId != null && !paramcChargeId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cChargeId", paramcChargeId));
    }
    // Filter: cActivityId (String) → column C_Activity_ID
    String paramcActivityId = request.getParameter("cActivityId");
    if (paramcActivityId != null && !paramcActivityId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cActivityId", paramcActivityId));
    }
    // Filter: adOrgTrxId (String) → column AD_OrgTrx_ID
    String paramadOrgTrxId = request.getParameter("adOrgTrxId");
    if (paramadOrgTrxId != null && !paramadOrgTrxId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("adOrgTrxId", paramadOrgTrxId));
    }
    // Filter: quotationId (String) → column Quotation_ID
    String paramquotationId = request.getParameter("quotationId");
    if (paramquotationId != null && !paramquotationId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("quotationId", paramquotationId));
    }
    // Filter: cancelledorderId (String) → column Cancelledorder_id
    String paramcancelledorderId = request.getParameter("cancelledorderId");
    if (paramcancelledorderId != null && !paramcancelledorderId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cancelledorderId", paramcancelledorderId));
    }
    // Filter: replacedorderId (String) → column Replacedorder_id
    String paramreplacedorderId = request.getParameter("replacedorderId");
    if (paramreplacedorderId != null && !paramreplacedorderId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("replacedorderId", paramreplacedorderId));
    }
    // Filter: bpartnerExtRef (String) → column BPartner_ExtRef
    String parambpartnerExtRef = request.getParameter("bpartnerExtRef");
    if (parambpartnerExtRef != null && !parambpartnerExtRef.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("bpartnerExtRef", parambpartnerExtRef));
    }
    // Filter: cProjectId (String) → column C_Project_ID
    String paramcProjectId = request.getParameter("cProjectId");
    if (paramcProjectId != null && !paramcProjectId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cProjectId", paramcProjectId));
    }
    // Filter: cCostcenterId (String) → column C_Costcenter_ID
    String paramcCostcenterId = request.getParameter("cCostcenterId");
    if (paramcCostcenterId != null && !paramcCostcenterId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cCostcenterId", paramcCostcenterId));
    }
    // Filter: aAssetId (String) → column A_Asset_ID
    String paramaAssetId = request.getParameter("aAssetId");
    if (paramaAssetId != null && !paramaAssetId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("aAssetId", paramaAssetId));
    }
    // Filter: user1Id (String) → column User1_ID
    String paramuser1Id = request.getParameter("user1Id");
    if (paramuser1Id != null && !paramuser1Id.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("user1Id", paramuser1Id));
    }
    // Filter: user2Id (String) → column User2_ID
    String paramuser2Id = request.getParameter("user2Id");
    if (paramuser2Id != null && !paramuser2Id.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("user2Id", paramuser2Id));
    }
    // Filter: dropShipLocationId (String) → column DropShip_Location_ID
    String paramdropShipLocationId = request.getParameter("dropShipLocationId");
    if (paramdropShipLocationId != null && !paramdropShipLocationId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("dropShipLocationId", paramdropShipLocationId));
    }
    // Filter: dropShipBpartnerId (String) → column DropShip_BPartner_ID
    String paramdropShipBpartnerId = request.getParameter("dropShipBpartnerId");
    if (paramdropShipBpartnerId != null && !paramdropShipBpartnerId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("dropShipBpartnerId", paramdropShipBpartnerId));
    }
    // Filter: dropShipUserId (String) → column DropShip_User_ID
    String paramdropShipUserId = request.getParameter("dropShipUserId");
    if (paramdropShipUserId != null && !paramdropShipUserId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("dropShipUserId", paramdropShipUserId));
    }
    // Filter: cIncotermsId (String) → column C_Incoterms_ID
    String paramcIncotermsId = request.getParameter("cIncotermsId");
    if (paramcIncotermsId != null && !paramcIncotermsId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cIncotermsId", paramcIncotermsId));
    }

    response.setContentType(APPLICATION_JSON);
    JSONObject result = new JSONObject();
    JSONArray data = new JSONArray();
    for (Order entity : criteria.list()) {
      JSONObject item = new JSONObject();
      item.put("id", entity.getId());
      item.put("identifier", entity.getIdentifier());
      data.put(item);
    }
    result.put("data", data);
    result.put("count", data.length());
    response.getWriter().write(result.toString());
  }

  private void getById(String id, HttpServletResponse response) throws Exception {
    Order entity = OBDal.getInstance().get(Order.class, id);
    response.setContentType(APPLICATION_JSON);
    if (entity == null) {
      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
      response.getWriter().write("{\"error\":\"cOrder not found\",\"id\":\"" + id + "\"}");
      return;
    }
    JSONObject result = new JSONObject();
    result.put("id", entity.getId());
    result.put("identifier", entity.getIdentifier());
    // TODO(vertical-slice): map all DTO fields from entity
    response.getWriter().write(result.toString());
  }
}
