// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.handler;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import org.openbravo.model.common.order.OrderReplacement;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: COrderReplacementHandler
 *
 * Entity: cOrderReplacement (C_Order_Replacement)
 * OBDal class: OrderReplacement
 */
public class COrderReplacementHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";

  @Override
  public String getBasePath() {
    return "/cOrderReplacement";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement create for OrderReplacement
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"POST not yet implemented for cOrderReplacement\"}");
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement update for OrderReplacement
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for cOrderReplacement\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement delete for OrderReplacement
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for cOrderReplacement\"}");
  }

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    OBCriteria<OrderReplacement> criteria = OBDal.getInstance().createCriteria(OrderReplacement.class);
    criteria.setMaxResults(100);

    // Filter: cReplacementId (String) → column C_Replacement_ID
    String paramcReplacementId = request.getParameter("cReplacementId");
    if (paramcReplacementId != null && !paramcReplacementId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cReplacementId", paramcReplacementId));
    }

    response.setContentType(APPLICATION_JSON);
    JSONObject result = new JSONObject();
    JSONArray data = new JSONArray();
    for (OrderReplacement entity : criteria.list()) {
      JSONObject item = new JSONObject();
      item.put("id", entity.getId());
      item.put("identifier", entity.getIdentifier());
      data.put(item);
    }
    result.put("data", data);
    result.put("count", data.length());
    response.getWriter().write(result.toString());
  }

  private void getById(String id, HttpServletResponse response) throws Exception {
    OrderReplacement entity = OBDal.getInstance().get(OrderReplacement.class, id);
    response.setContentType(APPLICATION_JSON);
    if (entity == null) {
      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
      response.getWriter().write("{\"error\":\"cOrderReplacement not found\",\"id\":\"" + id + "\"}");
      return;
    }
    JSONObject result = new JSONObject();
    result.put("id", entity.getId());
    result.put("identifier", entity.getIdentifier());
    // TODO(vertical-slice): map all DTO fields from entity
    response.getWriter().write(result.toString());
  }
}
