// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.handler;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import org.openbravo.model.common.order.OrderLine;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: COrderLineHandler
 *
 * Entity: cOrderLine (C_OrderLine)
 * OBDal class: OrderLine
 */
public class COrderLineHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";

  @Override
  public String getBasePath() {
    return "/cOrderLine";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement create for OrderLine
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"POST not yet implemented for cOrderLine\"}");
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement update for OrderLine
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for cOrderLine\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement delete for OrderLine
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for cOrderLine\"}");
  }

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    OBCriteria<OrderLine> criteria = OBDal.getInstance().createCriteria(OrderLine.class);
    criteria.setMaxResults(100);

    // Filter: mProductId (String) → column M_Product_ID
    String parammProductId = request.getParameter("mProductId");
    if (parammProductId != null && !parammProductId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mProductId", parammProductId));
    }
    // Filter: cAum (String) → column C_Aum
    String paramcAum = request.getParameter("cAum");
    if (paramcAum != null && !paramcAum.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cAum", paramcAum));
    }
    // Filter: cUomId (String) → column C_UOM_ID
    String paramcUomId = request.getParameter("cUomId");
    if (paramcUomId != null && !paramcUomId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cUomId", paramcUomId));
    }
    // Filter: priceActual (String) → column PriceActual
    String parampriceActual = request.getParameter("priceActual");
    if (parampriceActual != null && !parampriceActual.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("priceActual", parampriceActual));
    }
    // Filter: grossUnitPrice (String) → column Gross_Unit_Price
    String paramgrossUnitPrice = request.getParameter("grossUnitPrice");
    if (paramgrossUnitPrice != null && !paramgrossUnitPrice.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("grossUnitPrice", paramgrossUnitPrice));
    }
    // Filter: cTaxId (String) → column C_Tax_ID
    String paramcTaxId = request.getParameter("cTaxId");
    if (paramcTaxId != null && !paramcTaxId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cTaxId", paramcTaxId));
    }
    // Filter: priceList (String) → column PriceList
    String parampriceList = request.getParameter("priceList");
    if (parampriceList != null && !parampriceList.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("priceList", parampriceList));
    }
    // Filter: mWarehouseRuleId (String) → column M_Warehouse_Rule_ID
    String parammWarehouseRuleId = request.getParameter("mWarehouseRuleId");
    if (parammWarehouseRuleId != null && !parammWarehouseRuleId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mWarehouseRuleId", parammWarehouseRuleId));
    }
    // Filter: replacedorderlineId (String) → column Replacedorderline_id
    String paramreplacedorderlineId = request.getParameter("replacedorderlineId");
    if (paramreplacedorderlineId != null && !paramreplacedorderlineId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("replacedorderlineId", paramreplacedorderlineId));
    }
    // Filter: mProductUomId (String) → column M_Product_Uom_Id
    String parammProductUomId = request.getParameter("mProductUomId");
    if (parammProductUomId != null && !parammProductUomId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mProductUomId", parammProductUomId));
    }
    // Filter: priceStd (String) → column PriceStd
    String parampriceStd = request.getParameter("priceStd");
    if (parampriceStd != null && !parampriceStd.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("priceStd", parampriceStd));
    }
    // Filter: grosspricestd (String) → column grosspricestd
    String paramgrosspricestd = request.getParameter("grosspricestd");
    if (paramgrosspricestd != null && !paramgrosspricestd.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("grosspricestd", paramgrosspricestd));
    }
    // Filter: quotationlineId (String) → column Quotationline_ID
    String paramquotationlineId = request.getParameter("quotationlineId");
    if (paramquotationlineId != null && !paramquotationlineId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("quotationlineId", paramquotationlineId));
    }
    // Filter: cProjectId (String) → column C_Project_ID
    String paramcProjectId = request.getParameter("cProjectId");
    if (paramcProjectId != null && !paramcProjectId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cProjectId", paramcProjectId));
    }
    // Filter: cCostcenterId (String) → column C_Costcenter_ID
    String paramcCostcenterId = request.getParameter("cCostcenterId");
    if (paramcCostcenterId != null && !paramcCostcenterId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cCostcenterId", paramcCostcenterId));
    }
    // Filter: aAssetId (String) → column A_Asset_ID
    String paramaAssetId = request.getParameter("aAssetId");
    if (paramaAssetId != null && !paramaAssetId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("aAssetId", paramaAssetId));
    }
    // Filter: user1Id (String) → column User1_ID
    String paramuser1Id = request.getParameter("user1Id");
    if (paramuser1Id != null && !paramuser1Id.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("user1Id", paramuser1Id));
    }
    // Filter: user2Id (String) → column User2_ID
    String paramuser2Id = request.getParameter("user2Id");
    if (paramuser2Id != null && !paramuser2Id.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("user2Id", paramuser2Id));
    }

    response.setContentType(APPLICATION_JSON);
    JSONObject result = new JSONObject();
    JSONArray data = new JSONArray();
    for (OrderLine entity : criteria.list()) {
      JSONObject item = new JSONObject();
      item.put("id", entity.getId());
      item.put("identifier", entity.getIdentifier());
      data.put(item);
    }
    result.put("data", data);
    result.put("count", data.length());
    response.getWriter().write(result.toString());
  }

  private void getById(String id, HttpServletResponse response) throws Exception {
    OrderLine entity = OBDal.getInstance().get(OrderLine.class, id);
    response.setContentType(APPLICATION_JSON);
    if (entity == null) {
      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
      response.getWriter().write("{\"error\":\"cOrderLine not found\",\"id\":\"" + id + "\"}");
      return;
    }
    JSONObject result = new JSONObject();
    result.put("id", entity.getId());
    result.put("identifier", entity.getIdentifier());
    // TODO(vertical-slice): map all DTO fields from entity
    response.getWriter().write(result.toString());
  }
}
