// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.handler;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: COrderlineProductrelationHandler
 *
 * Entity: cOrderlineProductrelation (C_Orderline_Productrelation)
 * OBDal class: 
 */
public class COrderlineProductrelationHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";

  @Override
  public String getBasePath() {
    return "/cOrderlineProductrelation";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement create for 
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"POST not yet implemented for cOrderlineProductrelation\"}");
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement update for 
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for cOrderlineProductrelation\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement delete for 
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for cOrderlineProductrelation\"}");
  }

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    // No OBDal entity class available for cOrderlineProductrelation (table: C_Orderline_Productrelation)
    // This entity requires direct HQL or SQL queries
    response.setContentType(APPLICATION_JSON);
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.getWriter().write("{\"error\":\"No OBDal class for cOrderlineProductrelation\"}");
  }

  private void getById(String id, HttpServletResponse response) throws Exception {
    response.setContentType(APPLICATION_JSON);
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.getWriter().write("{\"error\":\"No OBDal class for cOrderlineProductrelation\"}");
  }
}
