// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.handler;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import org.openbravo.model.financialmgmt.payment.FIN_PaymentDetailV;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: FinPaymentDetailVHandler
 *
 * Entity: finPaymentDetailV (FIN_Payment_Detail_V)
 * OBDal class: FIN_PaymentDetailV
 */
public class FinPaymentDetailVHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";

  @Override
  public String getBasePath() {
    return "/finPaymentDetailV";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement create for FIN_PaymentDetailV
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"POST not yet implemented for finPaymentDetailV\"}");
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement update for FIN_PaymentDetailV
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for finPaymentDetailV\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement delete for FIN_PaymentDetailV
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for finPaymentDetailV\"}");
  }

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    OBCriteria<FIN_PaymentDetailV> criteria = OBDal.getInstance().createCriteria(FIN_PaymentDetailV.class);
    criteria.setMaxResults(100);

    // Filter: finPaymentId (String) → column FIN_Payment_ID
    String paramfinPaymentId = request.getParameter("finPaymentId");
    if (paramfinPaymentId != null && !paramfinPaymentId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("finPaymentId", paramfinPaymentId));
    }
    // Filter: emAprmDisplayedPaymmethId (String) → column EM_APRM_Displayed_Paymmeth_ID
    String paramemAprmDisplayedPaymmethId = request.getParameter("emAprmDisplayedPaymmethId");
    if (paramemAprmDisplayedPaymmethId != null && !paramemAprmDisplayedPaymmethId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("emAprmDisplayedPaymmethId", paramemAprmDisplayedPaymmethId));
    }
    // Filter: emAprmDisplayedAccId (String) → column EM_APRM_Displayed_Acc_ID
    String paramemAprmDisplayedAccId = request.getParameter("emAprmDisplayedAccId");
    if (paramemAprmDisplayedAccId != null && !paramemAprmDisplayedAccId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("emAprmDisplayedAccId", paramemAprmDisplayedAccId));
    }
    // Filter: finaccTxnConvertRate (String) → column Finacc_Txn_Convert_Rate
    String paramfinaccTxnConvertRate = request.getParameter("finaccTxnConvertRate");
    if (paramfinaccTxnConvertRate != null && !paramfinaccTxnConvertRate.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("finaccTxnConvertRate", paramfinaccTxnConvertRate));
    }

    response.setContentType(APPLICATION_JSON);
    JSONObject result = new JSONObject();
    JSONArray data = new JSONArray();
    for (FIN_PaymentDetailV entity : criteria.list()) {
      JSONObject item = new JSONObject();
      item.put("id", entity.getId());
      item.put("identifier", entity.getIdentifier());
      data.put(item);
    }
    result.put("data", data);
    result.put("count", data.length());
    response.getWriter().write(result.toString());
  }

  private void getById(String id, HttpServletResponse response) throws Exception {
    FIN_PaymentDetailV entity = OBDal.getInstance().get(FIN_PaymentDetailV.class, id);
    response.setContentType(APPLICATION_JSON);
    if (entity == null) {
      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
      response.getWriter().write("{\"error\":\"finPaymentDetailV not found\",\"id\":\"" + id + "\"}");
      return;
    }
    JSONObject result = new JSONObject();
    result.put("id", entity.getId());
    result.put("identifier", entity.getIdentifier());
    // TODO(vertical-slice): map all DTO fields from entity
    response.getWriter().write(result.toString());
  }
}
