// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-06T18:53:17.519Z
package com.etendoerp.go.salesorder.handler;

import javax.annotation.Generated;
import java.io.BufferedReader;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBQuery;
import org.openbravo.dal.service.OBDal;
import org.openbravo.model.common.order.Order;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: HeaderHandler
 *
 * Tab: Header
 * Entity: order (C_Order)
 * OBDal class: Order
 * Tab filter: salesTransaction=true
 */
@Generated(value = "schema-forge", date = "2026-03-06T18:53:17.519Z")
public class HeaderHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";
  private static final int DEFAULT_LIMIT = 100;
  private static final String TAB_HQL_FILTER = "salesTransaction=true";

  @Override
  public String getBasePath() {
    return "/sales-order/header";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      create(request, response);
    } catch (Exception e) {
      log.error("Error in POST {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for order\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for order\"}");
  }

  // ─── GET list ────────────────────────────────────────────────────────────────

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    StringBuilder hql = new StringBuilder(TAB_HQL_FILTER);

    String parambusinessPartner = request.getParameter("businessPartner");
    if (parambusinessPartner != null && !parambusinessPartner.isEmpty()) {
      hql.append(" AND businessPartner = '").append(parambusinessPartner.replace("'", "''")).append("'");
    }
    String parampartnerAddress = request.getParameter("partnerAddress");
    if (parampartnerAddress != null && !parampartnerAddress.isEmpty()) {
      hql.append(" AND partnerAddress = '").append(parampartnerAddress.replace("'", "''")).append("'");
    }
    String paramwarehouse = request.getParameter("warehouse");
    if (paramwarehouse != null && !paramwarehouse.isEmpty()) {
      hql.append(" AND warehouse = '").append(paramwarehouse.replace("'", "''")).append("'");
    }
    String parampriceList = request.getParameter("priceList");
    if (parampriceList != null && !parampriceList.isEmpty()) {
      hql.append(" AND priceList = '").append(parampriceList.replace("'", "''")).append("'");
    }
    String parampaymentTerms = request.getParameter("paymentTerms");
    if (parampaymentTerms != null && !parampaymentTerms.isEmpty()) {
      hql.append(" AND paymentTerms = '").append(parampaymentTerms.replace("'", "''")).append("'");
    }
    String parampaymentMethod = request.getParameter("paymentMethod");
    if (parampaymentMethod != null && !parampaymentMethod.isEmpty()) {
      hql.append(" AND paymentMethod = '").append(parampaymentMethod.replace("'", "''")).append("'");
    }
    String paraminvoiceAddress = request.getParameter("invoiceAddress");
    if (paraminvoiceAddress != null && !paraminvoiceAddress.isEmpty()) {
      hql.append(" AND invoiceAddress = '").append(paraminvoiceAddress.replace("'", "''")).append("'");
    }
    String paramdeliveryLocation = request.getParameter("deliveryLocation");
    if (paramdeliveryLocation != null && !paramdeliveryLocation.isEmpty()) {
      hql.append(" AND deliveryLocation = '").append(paramdeliveryLocation.replace("'", "''")).append("'");
    }
    String paramorderReference = request.getParameter("orderReference");
    if (paramorderReference != null && !paramorderReference.isEmpty()) {
      hql.append(" AND orderReference = '").append(paramorderReference.replace("'", "''")).append("'");
    }
    String paramsalesRepresentative = request.getParameter("salesRepresentative");
    if (paramsalesRepresentative != null && !paramsalesRepresentative.isEmpty()) {
      hql.append(" AND salesRepresentative = '").append(paramsalesRepresentative.replace("'", "''")).append("'");
    }
    String paramdescription = request.getParameter("description");
    if (paramdescription != null && !paramdescription.isEmpty()) {
      hql.append(" AND description = '").append(paramdescription.replace("'", "''")).append("'");
    }
    String paramdocumentNo = request.getParameter("documentNo");
    if (paramdocumentNo != null && !paramdocumentNo.isEmpty()) {
      hql.append(" AND documentNo = '").append(paramdocumentNo.replace("'", "''")).append("'");
    }
    String paramdocumentStatus = request.getParameter("documentStatus");
    if (paramdocumentStatus != null && !paramdocumentStatus.isEmpty()) {
      hql.append(" AND documentStatus = '").append(paramdocumentStatus.replace("'", "''")).append("'");
    }
    String paramcurrency = request.getParameter("currency");
    if (paramcurrency != null && !paramcurrency.isEmpty()) {
      hql.append(" AND currency = '").append(paramcurrency.replace("'", "''")).append("'");
    }

    OBQuery<Order> query = OBDal.getInstance().createQuery(Order.class, hql.toString());
    query.setMaxResult(DEFAULT_LIMIT);

    response.setContentType(APPLICATION_JSON);
    JSONObject result = new JSONObject();
    JSONArray data = new JSONArray();
    for (Order entity : query.list()) {
      data.put(entityToJson(entity));
    }
    result.put("data", data);
    result.put("count", data.length());
    response.getWriter().write(result.toString());
  }

  // ─── GET by ID ───────────────────────────────────────────────────────────────

  private void getById(String id, HttpServletResponse response) throws Exception {
    // Use OBQuery with filter to respect tab scope + security
    String hql = TAB_HQL_FILTER + " AND id = '" + id.replace("'", "''") + "'";
    OBQuery<Order> query = OBDal.getInstance().createQuery(Order.class, hql);
    query.setMaxResult(1);
    java.util.List<Order> results = query.list();
    Order entity = results.isEmpty() ? null : results.get(0);
    response.setContentType(APPLICATION_JSON);
    if (entity == null) {
      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
      response.getWriter().write("{\"error\":\"order not found\",\"id\":\"" + id + "\"}");
      return;
    }
    response.getWriter().write(entityToJson(entity).toString());
  }

  // ─── POST create ─────────────────────────────────────────────────────────────

  private void create(HttpServletRequest request, HttpServletResponse response) throws Exception {
    StringBuilder sb = new StringBuilder();
    try (BufferedReader reader = request.getReader()) {
      String line;
      while ((line = reader.readLine()) != null) {
        sb.append(line);
      }
    }
    JSONObject body = new JSONObject(sb.toString());

    Order entity = new Order();
    entity.setOrganization(OBContext.getOBContext().getCurrentOrganization());
    entity.setClient(OBContext.getOBContext().getCurrentClient());

    entity.set("salesTransaction", true);

    // Set system-derived fields
    {
      OBQuery<org.openbravo.model.common.enterprise.DocumentType> dtQuery = OBDal.getInstance()
          .createQuery(org.openbravo.model.common.enterprise.DocumentType.class,
              "documentCategory = 'SOO' AND client.id = :clientId AND name = 'Standard Order'");
      dtQuery.setNamedParameter("clientId", OBContext.getOBContext().getCurrentClient().getId());
      dtQuery.setMaxResult(1);
      org.openbravo.model.common.enterprise.DocumentType docType = dtQuery.uniqueResult();
      if (docType != null) {
        entity.set("transactionDocument", docType);
      }
    }
    {
      OBQuery<org.openbravo.model.common.enterprise.DocumentType> dtQuery = OBDal.getInstance()
          .createQuery(org.openbravo.model.common.enterprise.DocumentType.class,
              "documentCategory = 'SOO' AND client.id = :clientId AND name = 'Standard Order'");
      dtQuery.setNamedParameter("clientId", OBContext.getOBContext().getCurrentClient().getId());
      dtQuery.setMaxResult(1);
      org.openbravo.model.common.enterprise.DocumentType docType = dtQuery.uniqueResult();
      if (docType != null) {
        entity.set("documentType", docType);
      }
    }
    entity.set("salesTransaction", true);
    entity.set("processed", false);
    entity.set("invoiceTerms", "D");
    entity.set("deliveryTerms", "A");
    entity.set("deliveryMethod", "D");
    entity.set("freightCostRule", "I");
    entity.set("priority", "5");
    entity.set("formOfPayment", "P");

    // Set editable fields from request body
    if (body.has("businessPartner")) {
      entity.set("businessPartner", OBDal.getInstance().getProxy(entity.getEntity().getProperty("businessPartner").getReferencedProperty().getEntity().getName(), body.getString("businessPartner")));
    }
    if (body.has("partnerAddress")) {
      entity.set("partnerAddress", OBDal.getInstance().getProxy(entity.getEntity().getProperty("partnerAddress").getReferencedProperty().getEntity().getName(), body.getString("partnerAddress")));
    }
    if (body.has("orderDate")) {
      entity.set("orderDate", new java.text.SimpleDateFormat("yyyy-MM-dd").parse(body.getString("orderDate")));
    }
    if (body.has("scheduledDeliveryDate")) {
      entity.set("scheduledDeliveryDate", new java.text.SimpleDateFormat("yyyy-MM-dd").parse(body.getString("scheduledDeliveryDate")));
    }
    if (body.has("warehouse")) {
      entity.set("warehouse", OBDal.getInstance().getProxy(entity.getEntity().getProperty("warehouse").getReferencedProperty().getEntity().getName(), body.getString("warehouse")));
    }
    if (body.has("priceList")) {
      entity.set("priceList", OBDal.getInstance().getProxy(entity.getEntity().getProperty("priceList").getReferencedProperty().getEntity().getName(), body.getString("priceList")));
    }
    if (body.has("paymentTerms")) {
      entity.set("paymentTerms", OBDal.getInstance().getProxy(entity.getEntity().getProperty("paymentTerms").getReferencedProperty().getEntity().getName(), body.getString("paymentTerms")));
    }
    if (body.has("paymentMethod")) {
      entity.set("paymentMethod", OBDal.getInstance().getProxy(entity.getEntity().getProperty("paymentMethod").getReferencedProperty().getEntity().getName(), body.getString("paymentMethod")));
    }
    if (body.has("invoiceAddress")) {
      entity.set("invoiceAddress", OBDal.getInstance().getProxy(entity.getEntity().getProperty("invoiceAddress").getReferencedProperty().getEntity().getName(), body.getString("invoiceAddress")));
    }
    if (body.has("deliveryLocation")) {
      entity.set("deliveryLocation", OBDal.getInstance().getProxy(entity.getEntity().getProperty("deliveryLocation").getReferencedProperty().getEntity().getName(), body.getString("deliveryLocation")));
    }
    if (body.has("orderReference")) {
      entity.set("orderReference", body.getString("orderReference"));
    }
    if (body.has("salesRepresentative")) {
      entity.set("salesRepresentative", OBDal.getInstance().getProxy(entity.getEntity().getProperty("salesRepresentative").getReferencedProperty().getEntity().getName(), body.getString("salesRepresentative")));
    }
    if (body.has("description")) {
      entity.set("description", body.getString("description"));
    }

    // Copy-field derivations (must run after editable fields are set)
    if (entity.get("orderDate") != null) {
      entity.set("accountingDate", entity.get("orderDate"));
    }

    OBDal.getInstance().save(entity);
    OBDal.getInstance().flush();

    response.setStatus(HttpServletResponse.SC_CREATED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write(entityToJson(entity).toString());
  }

  // ─── Entity → JSON mapping ──────────────────────────────────────────────────

  private JSONObject entityToJson(Order entity) throws Exception {
    JSONObject json = new JSONObject();
    json.put("id", entity.getId());
    json.put("identifier", entity.getIdentifier());
    if (entity.get("businessPartner") != null) {
      Object businessPartnerRef = entity.get("businessPartner");
      if (businessPartnerRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject businessPartnerJson = new JSONObject();
        businessPartnerJson.put("id", ((org.openbravo.base.structure.BaseOBObject) businessPartnerRef).getId());
        businessPartnerJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) businessPartnerRef).getIdentifier());
        json.put("businessPartner", businessPartnerJson);
      } else {
        json.put("businessPartner", entity.get("businessPartner"));
      }
    }
    if (entity.get("partnerAddress") != null) {
      Object partnerAddressRef = entity.get("partnerAddress");
      if (partnerAddressRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject partnerAddressJson = new JSONObject();
        partnerAddressJson.put("id", ((org.openbravo.base.structure.BaseOBObject) partnerAddressRef).getId());
        partnerAddressJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) partnerAddressRef).getIdentifier());
        json.put("partnerAddress", partnerAddressJson);
      } else {
        json.put("partnerAddress", entity.get("partnerAddress"));
      }
    }
    if (entity.get("orderDate") != null) {
      json.put("orderDate", entity.get("orderDate"));
    }
    if (entity.get("scheduledDeliveryDate") != null) {
      json.put("scheduledDeliveryDate", entity.get("scheduledDeliveryDate"));
    }
    if (entity.get("warehouse") != null) {
      Object warehouseRef = entity.get("warehouse");
      if (warehouseRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject warehouseJson = new JSONObject();
        warehouseJson.put("id", ((org.openbravo.base.structure.BaseOBObject) warehouseRef).getId());
        warehouseJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) warehouseRef).getIdentifier());
        json.put("warehouse", warehouseJson);
      } else {
        json.put("warehouse", entity.get("warehouse"));
      }
    }
    if (entity.get("priceList") != null) {
      Object priceListRef = entity.get("priceList");
      if (priceListRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject priceListJson = new JSONObject();
        priceListJson.put("id", ((org.openbravo.base.structure.BaseOBObject) priceListRef).getId());
        priceListJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) priceListRef).getIdentifier());
        json.put("priceList", priceListJson);
      } else {
        json.put("priceList", entity.get("priceList"));
      }
    }
    if (entity.get("paymentTerms") != null) {
      Object paymentTermsRef = entity.get("paymentTerms");
      if (paymentTermsRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject paymentTermsJson = new JSONObject();
        paymentTermsJson.put("id", ((org.openbravo.base.structure.BaseOBObject) paymentTermsRef).getId());
        paymentTermsJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) paymentTermsRef).getIdentifier());
        json.put("paymentTerms", paymentTermsJson);
      } else {
        json.put("paymentTerms", entity.get("paymentTerms"));
      }
    }
    if (entity.get("paymentMethod") != null) {
      Object paymentMethodRef = entity.get("paymentMethod");
      if (paymentMethodRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject paymentMethodJson = new JSONObject();
        paymentMethodJson.put("id", ((org.openbravo.base.structure.BaseOBObject) paymentMethodRef).getId());
        paymentMethodJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) paymentMethodRef).getIdentifier());
        json.put("paymentMethod", paymentMethodJson);
      } else {
        json.put("paymentMethod", entity.get("paymentMethod"));
      }
    }
    if (entity.get("invoiceAddress") != null) {
      Object invoiceAddressRef = entity.get("invoiceAddress");
      if (invoiceAddressRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject invoiceAddressJson = new JSONObject();
        invoiceAddressJson.put("id", ((org.openbravo.base.structure.BaseOBObject) invoiceAddressRef).getId());
        invoiceAddressJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) invoiceAddressRef).getIdentifier());
        json.put("invoiceAddress", invoiceAddressJson);
      } else {
        json.put("invoiceAddress", entity.get("invoiceAddress"));
      }
    }
    if (entity.get("deliveryLocation") != null) {
      Object deliveryLocationRef = entity.get("deliveryLocation");
      if (deliveryLocationRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject deliveryLocationJson = new JSONObject();
        deliveryLocationJson.put("id", ((org.openbravo.base.structure.BaseOBObject) deliveryLocationRef).getId());
        deliveryLocationJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) deliveryLocationRef).getIdentifier());
        json.put("deliveryLocation", deliveryLocationJson);
      } else {
        json.put("deliveryLocation", entity.get("deliveryLocation"));
      }
    }
    if (entity.get("orderReference") != null) {
      json.put("orderReference", entity.get("orderReference"));
    }
    if (entity.get("salesRepresentative") != null) {
      Object salesRepresentativeRef = entity.get("salesRepresentative");
      if (salesRepresentativeRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject salesRepresentativeJson = new JSONObject();
        salesRepresentativeJson.put("id", ((org.openbravo.base.structure.BaseOBObject) salesRepresentativeRef).getId());
        salesRepresentativeJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) salesRepresentativeRef).getIdentifier());
        json.put("salesRepresentative", salesRepresentativeJson);
      } else {
        json.put("salesRepresentative", entity.get("salesRepresentative"));
      }
    }
    if (entity.get("description") != null) {
      json.put("description", entity.get("description"));
    }
    if (entity.get("documentNo") != null) {
      json.put("documentNo", entity.get("documentNo"));
    }
    if (entity.get("documentStatus") != null) {
      json.put("documentStatus", entity.get("documentStatus"));
    }
    if (entity.get("grandTotalAmount") != null) {
      json.put("grandTotalAmount", entity.get("grandTotalAmount"));
    }
    if (entity.get("summedLineAmount") != null) {
      json.put("summedLineAmount", entity.get("summedLineAmount"));
    }
    if (entity.get("currency") != null) {
      Object currencyRef = entity.get("currency");
      if (currencyRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject currencyJson = new JSONObject();
        currencyJson.put("id", ((org.openbravo.base.structure.BaseOBObject) currencyRef).getId());
        currencyJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) currencyRef).getIdentifier());
        json.put("currency", currencyJson);
      } else {
        json.put("currency", entity.get("currency"));
      }
    }
    if (entity.get("delivered") != null) {
      json.put("delivered", entity.get("delivered"));
    }
    return json;
  }
}
