// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-06T18:53:17.519Z
package com.etendoerp.go.salesorder.handler;

import javax.annotation.Generated;
import java.io.BufferedReader;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBQuery;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import org.openbravo.model.common.order.OrderLine;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: LinesHandler
 *
 * Tab: Lines
 * Entity: orderLine (C_OrderLine)
 * OBDal class: OrderLine
 */
@Generated(value = "schema-forge", date = "2026-03-06T18:53:17.519Z")
public class LinesHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";
  private static final int DEFAULT_LIMIT = 100;

  @Override
  public String getBasePath() {
    return "/sales-order/lines";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      create(request, response);
    } catch (Exception e) {
      log.error("Error in POST {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for orderLine\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for orderLine\"}");
  }

  // ─── GET list ────────────────────────────────────────────────────────────────

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    OBCriteria<OrderLine> criteria = OBDal.getInstance().createCriteria(OrderLine.class);
    criteria.setMaxResults(DEFAULT_LIMIT);

    String paramproduct = request.getParameter("product");
    if (paramproduct != null && !paramproduct.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("product", paramproduct));
    }
    String paramtax = request.getParameter("tax");
    if (paramtax != null && !paramtax.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("tax", paramtax));
    }
    String paramdescription = request.getParameter("description");
    if (paramdescription != null && !paramdescription.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("description", paramdescription));
    }
    String paramuOM = request.getParameter("uOM");
    if (paramuOM != null && !paramuOM.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("uOM", paramuOM));
    }

    response.setContentType(APPLICATION_JSON);
    JSONObject result = new JSONObject();
    JSONArray data = new JSONArray();
    for (OrderLine entity : criteria.list()) {
      data.put(entityToJson(entity));
    }
    result.put("data", data);
    result.put("count", data.length());
    response.getWriter().write(result.toString());
  }

  // ─── GET by ID ───────────────────────────────────────────────────────────────

  private void getById(String id, HttpServletResponse response) throws Exception {
    OrderLine entity = OBDal.getInstance().get(OrderLine.class, id);
    response.setContentType(APPLICATION_JSON);
    if (entity == null) {
      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
      response.getWriter().write("{\"error\":\"orderLine not found\",\"id\":\"" + id + "\"}");
      return;
    }
    response.getWriter().write(entityToJson(entity).toString());
  }

  // ─── POST create ─────────────────────────────────────────────────────────────

  private void create(HttpServletRequest request, HttpServletResponse response) throws Exception {
    StringBuilder sb = new StringBuilder();
    try (BufferedReader reader = request.getReader()) {
      String line;
      while ((line = reader.readLine()) != null) {
        sb.append(line);
      }
    }
    JSONObject body = new JSONObject(sb.toString());

    OrderLine entity = new OrderLine();
    entity.setOrganization(OBContext.getOBContext().getCurrentOrganization());
    entity.setClient(OBContext.getOBContext().getCurrentClient());


    // Set system-derived fields

    // Set editable fields from request body
    if (body.has("product")) {
      entity.set("product", OBDal.getInstance().getProxy(entity.getEntity().getProperty("product").getReferencedProperty().getEntity().getName(), body.getString("product")));
    }
    if (body.has("orderedQuantity")) {
      entity.set("orderedQuantity", new BigDecimal(body.getString("orderedQuantity")));
    }
    if (body.has("unitPrice")) {
      entity.set("unitPrice", new BigDecimal(body.getString("unitPrice")));
    }
    if (body.has("tax")) {
      entity.set("tax", OBDal.getInstance().getProxy(entity.getEntity().getProperty("tax").getReferencedProperty().getEntity().getName(), body.getString("tax")));
    }
    if (body.has("discount")) {
      entity.set("discount", new BigDecimal(body.getString("discount")));
    }
    if (body.has("description")) {
      entity.set("description", body.getString("description"));
    }
    if (body.has("lineNo")) {
      entity.set("lineNo", (long) body.getInt("lineNo"));
    }

    // Copy-field derivations (must run after editable fields are set)

    OBDal.getInstance().save(entity);
    OBDal.getInstance().flush();

    response.setStatus(HttpServletResponse.SC_CREATED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write(entityToJson(entity).toString());
  }

  // ─── Entity → JSON mapping ──────────────────────────────────────────────────

  private JSONObject entityToJson(OrderLine entity) throws Exception {
    JSONObject json = new JSONObject();
    json.put("id", entity.getId());
    json.put("identifier", entity.getIdentifier());
    if (entity.get("product") != null) {
      Object productRef = entity.get("product");
      if (productRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject productJson = new JSONObject();
        productJson.put("id", ((org.openbravo.base.structure.BaseOBObject) productRef).getId());
        productJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) productRef).getIdentifier());
        json.put("product", productJson);
      } else {
        json.put("product", entity.get("product"));
      }
    }
    if (entity.get("orderedQuantity") != null) {
      json.put("orderedQuantity", entity.get("orderedQuantity"));
    }
    if (entity.get("unitPrice") != null) {
      json.put("unitPrice", entity.get("unitPrice"));
    }
    if (entity.get("tax") != null) {
      Object taxRef = entity.get("tax");
      if (taxRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject taxJson = new JSONObject();
        taxJson.put("id", ((org.openbravo.base.structure.BaseOBObject) taxRef).getId());
        taxJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) taxRef).getIdentifier());
        json.put("tax", taxJson);
      } else {
        json.put("tax", entity.get("tax"));
      }
    }
    if (entity.get("discount") != null) {
      json.put("discount", entity.get("discount"));
    }
    if (entity.get("description") != null) {
      json.put("description", entity.get("description"));
    }
    if (entity.get("lineNo") != null) {
      json.put("lineNo", entity.get("lineNo"));
    }
    if (entity.get("lineNetAmount") != null) {
      json.put("lineNetAmount", entity.get("lineNetAmount"));
    }
    if (entity.get("deliveredQuantity") != null) {
      json.put("deliveredQuantity", entity.get("deliveredQuantity"));
    }
    if (entity.get("uOM") != null) {
      Object uOMRef = entity.get("uOM");
      if (uOMRef instanceof org.openbravo.base.structure.BaseOBObject) {
        JSONObject uOMJson = new JSONObject();
        uOMJson.put("id", ((org.openbravo.base.structure.BaseOBObject) uOMRef).getId());
        uOMJson.put("identifier", ((org.openbravo.base.structure.BaseOBObject) uOMRef).getIdentifier());
        json.put("uOM", uOMJson);
      } else {
        json.put("uOM", entity.get("uOM"));
      }
    }
    return json;
  }
}
