// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.handler;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBCriteria;
import org.openbravo.dal.service.OBDal;
import org.openbravo.model.materialmgmt.onhandquantity.SOLReservedStock;

import com.etendoerp.go.rest.RequestHandler;

/**
 * Request Handler: MSolReservedStockVHandler
 *
 * Entity: mSolReservedStockV (M_SOL_Reserved_Stock_V)
 * OBDal class: SOLReservedStock
 */
public class MSolReservedStockVHandler implements RequestHandler {

  private static final Logger log = LogManager.getLogger();
  private static final String APPLICATION_JSON = "application/json;charset=UTF-8";

  @Override
  public String getBasePath() {
    return "/mSolReservedStockV";
  }

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    OBContext.setAdminMode(false);
    try {
      if (subPath != null && subPath.length() > 1) {
        String id = subPath.startsWith("/") ? subPath.substring(1) : subPath;
        getById(id, response);
      } else {
        list(request, response);
      }
    } catch (Exception e) {
      log.error("Error in GET {}", request.getPathInfo(), e);
      response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement create for SOLReservedStock
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"POST not yet implemented for mSolReservedStockV\"}");
  }

  @Override
  public void doPut(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement update for SOLReservedStock
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"PUT not yet implemented for mSolReservedStockV\"}");
  }

  @Override
  public void doDelete(HttpServletRequest request, HttpServletResponse response, String subPath) throws IOException {
    // TODO(vertical-slice): implement delete for SOLReservedStock
    response.setStatus(HttpServletResponse.SC_NOT_IMPLEMENTED);
    response.setContentType(APPLICATION_JSON);
    response.getWriter().write("{\"error\":\"DELETE not yet implemented for mSolReservedStockV\"}");
  }

  private void list(HttpServletRequest request, HttpServletResponse response) throws Exception {
    OBCriteria<SOLReservedStock> criteria = OBDal.getInstance().createCriteria(SOLReservedStock.class);
    criteria.setMaxResults(100);

    // Filter: mReservationId (String) → column M_Reservation_ID
    String parammReservationId = request.getParameter("mReservationId");
    if (parammReservationId != null && !parammReservationId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mReservationId", parammReservationId));
    }
    // Filter: mLocatorId (String) → column M_Locator_ID
    String parammLocatorId = request.getParameter("mLocatorId");
    if (parammLocatorId != null && !parammLocatorId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("mLocatorId", parammLocatorId));
    }
    // Filter: cOrderlineId (String) → column C_Orderline_ID
    String paramcOrderlineId = request.getParameter("cOrderlineId");
    if (paramcOrderlineId != null && !paramcOrderlineId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cOrderlineId", paramcOrderlineId));
    }
    // Filter: cBpartnerId (String) → column C_BPartner_ID
    String paramcBpartnerId = request.getParameter("cBpartnerId");
    if (paramcBpartnerId != null && !paramcBpartnerId.isEmpty()) {
      criteria.add(org.hibernate.criterion.Restrictions.eq("cBpartnerId", paramcBpartnerId));
    }

    response.setContentType(APPLICATION_JSON);
    JSONObject result = new JSONObject();
    JSONArray data = new JSONArray();
    for (SOLReservedStock entity : criteria.list()) {
      JSONObject item = new JSONObject();
      item.put("id", entity.getId());
      item.put("identifier", entity.getIdentifier());
      data.put(item);
    }
    result.put("data", data);
    result.put("count", data.length());
    response.getWriter().write(result.toString());
  }

  private void getById(String id, HttpServletResponse response) throws Exception {
    SOLReservedStock entity = OBDal.getInstance().get(SOLReservedStock.class, id);
    response.setContentType(APPLICATION_JSON);
    if (entity == null) {
      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
      response.getWriter().write("{\"error\":\"mSolReservedStockV not found\",\"id\":\"" + id + "\"}");
      return;
    }
    JSONObject result = new JSONObject();
    result.put("id", entity.getId());
    result.put("identifier", entity.getIdentifier());
    // TODO(vertical-slice): map all DTO fields from entity
    response.getWriter().write(result.toString());
  }
}
