// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Data Transfer Object: COrderReplacementDTO
 *
 * Version 1 — generated from curated schema.
 */
public class COrderReplacementDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private String cReplacementId;

  public COrderReplacementDTO() {
    // Default constructor
  }

  public String getCReplacementId() {
    return this.cReplacementId;
  }

  public void setCReplacementId(String cReplacementId) {
    this.cReplacementId = cReplacementId;
  }

}
