// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Data Transfer Object: FinPaymentDetailVDTO
 *
 * Version 1 — generated from curated schema.
 */
public class FinPaymentDetailVDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private String finPaymentId;
  private Date paymentdate;
  private Date duedate;
  private String emAprmDisplayedPaymmethId;
  private String emAprmDisplayedAccId;
  private BigDecimal expected;
  private BigDecimal paidamt;
  private BigDecimal writeoffamt;
  private BigDecimal expectedConverted;
  private BigDecimal paidConverted;
  private String finaccTxnConvertRate;
  private Boolean iscanceled;
  private String status;

  public FinPaymentDetailVDTO() {
    // Default constructor
  }

  public String getFinPaymentId() {
    return this.finPaymentId;
  }

  public void setFinPaymentId(String finPaymentId) {
    this.finPaymentId = finPaymentId;
  }

  public Date getPaymentdate() {
    return this.paymentdate;
  }

  public void setPaymentdate(Date paymentdate) {
    this.paymentdate = paymentdate;
  }

  public Date getDuedate() {
    return this.duedate;
  }

  public void setDuedate(Date duedate) {
    this.duedate = duedate;
  }

  public String getEmAprmDisplayedPaymmethId() {
    return this.emAprmDisplayedPaymmethId;
  }

  public void setEmAprmDisplayedPaymmethId(String emAprmDisplayedPaymmethId) {
    this.emAprmDisplayedPaymmethId = emAprmDisplayedPaymmethId;
  }

  public String getEmAprmDisplayedAccId() {
    return this.emAprmDisplayedAccId;
  }

  public void setEmAprmDisplayedAccId(String emAprmDisplayedAccId) {
    this.emAprmDisplayedAccId = emAprmDisplayedAccId;
  }

  public BigDecimal getExpected() {
    return this.expected;
  }

  public void setExpected(BigDecimal expected) {
    this.expected = expected;
  }

  public BigDecimal getPaidamt() {
    return this.paidamt;
  }

  public void setPaidamt(BigDecimal paidamt) {
    this.paidamt = paidamt;
  }

  public BigDecimal getWriteoffamt() {
    return this.writeoffamt;
  }

  public void setWriteoffamt(BigDecimal writeoffamt) {
    this.writeoffamt = writeoffamt;
  }

  public BigDecimal getExpectedConverted() {
    return this.expectedConverted;
  }

  public void setExpectedConverted(BigDecimal expectedConverted) {
    this.expectedConverted = expectedConverted;
  }

  public BigDecimal getPaidConverted() {
    return this.paidConverted;
  }

  public void setPaidConverted(BigDecimal paidConverted) {
    this.paidConverted = paidConverted;
  }

  public String getFinaccTxnConvertRate() {
    return this.finaccTxnConvertRate;
  }

  public void setFinaccTxnConvertRate(String finaccTxnConvertRate) {
    this.finaccTxnConvertRate = finaccTxnConvertRate;
  }

  public Boolean getIscanceled() {
    return this.iscanceled;
  }

  public void setIscanceled(Boolean iscanceled) {
    this.iscanceled = iscanceled;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

}
