// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-05T19:33:32.802Z
package com.etendoerp.go.salesorder.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Data Transfer Object: FinPaymentSchedOrdVDTO
 *
 * Version 1 — generated from curated schema.
 */
public class FinPaymentSchedOrdVDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private Date duedate;
  private String finPaymentmethodId;
  private BigDecimal expected;
  private BigDecimal received;
  private BigDecimal outstanding;
  private Date lastpayment;
  private Integer numberofpayments;
  private String cCurrencyId;

  public FinPaymentSchedOrdVDTO() {
    // Default constructor
  }

  public Date getDuedate() {
    return this.duedate;
  }

  public void setDuedate(Date duedate) {
    this.duedate = duedate;
  }

  public String getFinPaymentmethodId() {
    return this.finPaymentmethodId;
  }

  public void setFinPaymentmethodId(String finPaymentmethodId) {
    this.finPaymentmethodId = finPaymentmethodId;
  }

  public BigDecimal getExpected() {
    return this.expected;
  }

  public void setExpected(BigDecimal expected) {
    this.expected = expected;
  }

  public BigDecimal getReceived() {
    return this.received;
  }

  public void setReceived(BigDecimal received) {
    this.received = received;
  }

  public BigDecimal getOutstanding() {
    return this.outstanding;
  }

  public void setOutstanding(BigDecimal outstanding) {
    this.outstanding = outstanding;
  }

  public Date getLastpayment() {
    return this.lastpayment;
  }

  public void setLastpayment(Date lastpayment) {
    this.lastpayment = lastpayment;
  }

  public Integer getNumberofpayments() {
    return this.numberofpayments;
  }

  public void setNumberofpayments(Integer numberofpayments) {
    this.numberofpayments = numberofpayments;
  }

  public String getCCurrencyId() {
    return this.cCurrencyId;
  }

  public void setCCurrencyId(String cCurrencyId) {
    this.cCurrencyId = cCurrencyId;
  }

}
