// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-06T18:53:17.519Z
package com.etendoerp.go.salesorder.dto;

import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Data Transfer Object: OrderLineDTO
 *
 * Version 1 — generated from curated schema.
 */
@Generated(value = "schema-forge", date = "2026-03-06T18:53:17.519Z")
public class OrderLineDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private String product;
  private BigDecimal orderedQuantity;
  private BigDecimal unitPrice;
  private String tax;
  private BigDecimal discount;
  private String description;
  private Integer lineNo;
  private BigDecimal lineNetAmount;
  private BigDecimal deliveredQuantity;
  private String uOM;

  public OrderLineDTO() {
    // Default constructor
  }

  public String getProduct() {
    return this.product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public BigDecimal getOrderedQuantity() {
    return this.orderedQuantity;
  }

  public void setOrderedQuantity(BigDecimal orderedQuantity) {
    this.orderedQuantity = orderedQuantity;
  }

  public BigDecimal getUnitPrice() {
    return this.unitPrice;
  }

  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }

  public String getTax() {
    return this.tax;
  }

  public void setTax(String tax) {
    this.tax = tax;
  }

  public BigDecimal getDiscount() {
    return this.discount;
  }

  public void setDiscount(BigDecimal discount) {
    this.discount = discount;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Integer getLineNo() {
    return this.lineNo;
  }

  public void setLineNo(Integer lineNo) {
    this.lineNo = lineNo;
  }

  public BigDecimal getLineNetAmount() {
    return this.lineNetAmount;
  }

  public void setLineNetAmount(BigDecimal lineNetAmount) {
    this.lineNetAmount = lineNetAmount;
  }

  public BigDecimal getDeliveredQuantity() {
    return this.deliveredQuantity;
  }

  public void setDeliveredQuantity(BigDecimal deliveredQuantity) {
    this.deliveredQuantity = deliveredQuantity;
  }

  public String getUOM() {
    return this.uOM;
  }

  public void setUOM(String uOM) {
    this.uOM = uOM;
  }

}
