// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// DTO version: 1
// Generated: 2026-03-06T18:53:17.519Z
package com.etendoerp.go.salesorder.dto;

import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Data Transfer Object: OrderDTO
 *
 * Version 1 — generated from curated schema.
 */
@Generated(value = "schema-forge", date = "2026-03-06T18:53:17.519Z")
public class OrderDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  private String businessPartner;
  private String partnerAddress;
  private Date orderDate;
  private Date scheduledDeliveryDate;
  private String warehouse;
  private String priceList;
  private String paymentTerms;
  private String paymentMethod;
  private String invoiceAddress;
  private String deliveryLocation;
  private String orderReference;
  private String salesRepresentative;
  private String description;
  private String documentNo;
  private String documentStatus;
  private BigDecimal grandTotalAmount;
  private BigDecimal summedLineAmount;
  private String currency;
  private Boolean delivered;

  public OrderDTO() {
    // Default constructor
  }

  public String getBusinessPartner() {
    return this.businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public String getPartnerAddress() {
    return this.partnerAddress;
  }

  public void setPartnerAddress(String partnerAddress) {
    this.partnerAddress = partnerAddress;
  }

  public Date getOrderDate() {
    return this.orderDate;
  }

  public void setOrderDate(Date orderDate) {
    this.orderDate = orderDate;
  }

  public Date getScheduledDeliveryDate() {
    return this.scheduledDeliveryDate;
  }

  public void setScheduledDeliveryDate(Date scheduledDeliveryDate) {
    this.scheduledDeliveryDate = scheduledDeliveryDate;
  }

  public String getWarehouse() {
    return this.warehouse;
  }

  public void setWarehouse(String warehouse) {
    this.warehouse = warehouse;
  }

  public String getPriceList() {
    return this.priceList;
  }

  public void setPriceList(String priceList) {
    this.priceList = priceList;
  }

  public String getPaymentTerms() {
    return this.paymentTerms;
  }

  public void setPaymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

  public String getPaymentMethod() {
    return this.paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public String getInvoiceAddress() {
    return this.invoiceAddress;
  }

  public void setInvoiceAddress(String invoiceAddress) {
    this.invoiceAddress = invoiceAddress;
  }

  public String getDeliveryLocation() {
    return this.deliveryLocation;
  }

  public void setDeliveryLocation(String deliveryLocation) {
    this.deliveryLocation = deliveryLocation;
  }

  public String getOrderReference() {
    return this.orderReference;
  }

  public void setOrderReference(String orderReference) {
    this.orderReference = orderReference;
  }

  public String getSalesRepresentative() {
    return this.salesRepresentative;
  }

  public void setSalesRepresentative(String salesRepresentative) {
    this.salesRepresentative = salesRepresentative;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getDocumentNo() {
    return this.documentNo;
  }

  public void setDocumentNo(String documentNo) {
    this.documentNo = documentNo;
  }

  public String getDocumentStatus() {
    return this.documentStatus;
  }

  public void setDocumentStatus(String documentStatus) {
    this.documentStatus = documentStatus;
  }

  public BigDecimal getGrandTotalAmount() {
    return this.grandTotalAmount;
  }

  public void setGrandTotalAmount(BigDecimal grandTotalAmount) {
    this.grandTotalAmount = grandTotalAmount;
  }

  public BigDecimal getSummedLineAmount() {
    return this.summedLineAmount;
  }

  public void setSummedLineAmount(BigDecimal summedLineAmount) {
    this.summedLineAmount = summedLineAmount;
  }

  public String getCurrency() {
    return this.currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Boolean getDelivered() {
    return this.delivered;
  }

  public void setDelivered(Boolean delivered) {
    this.delivered = delivered;
  }

}
