/*
 * *************************************************************************
 * The contents of this file are subject to the Etendo License
 * (the "License"), you may not use this file except in compliance with
 * the License.
 * You may obtain a copy of the License at
 * https://github.com/etendosoftware/etendo_core/blob/main/legal/Etendo_license.txt
 * Software distributed under the License is distributed on an
 * "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing rights
 * and limitations under the License.
 * All portions are Copyright (C) 2021-2026 FUTIT SERVICES, S.L
 * All Rights Reserved.
 * Contributor(s): Futit Services S.L.
 * *************************************************************************
 */

package com.etendoerp.go.rest;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Base64;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.base.HttpBaseServlet;
import org.openbravo.base.secureApp.VariablesSecureApp;
import org.openbravo.dal.core.OBContext;
import org.openbravo.dal.service.OBDal;
import org.openbravo.erpCommon.businessUtility.InitialClientSetup;
import org.openbravo.erpCommon.businessUtility.InitialOrgSetup;
import org.openbravo.erpCommon.utility.OBError;
import org.openbravo.model.ad.access.Role;
import org.openbravo.model.ad.access.User;
import org.openbravo.model.ad.access.UserRoles;
import org.openbravo.model.ad.system.Client;
import org.openbravo.model.common.enterprise.Organization;

import com.etendoerp.go.common.CorsUtils;
import com.smf.securewebservices.utils.SecureWebServicesUtils;

/**
 * EtendoGo JWT Servlet — account management for platform users.
 *
 * Mapped to /sws/go/* via AD_MODEL_OBJECT_MAPPING (ID: FB313FD86E7846F8992F4C61B7230066).
 *
 * Endpoints:
 *   POST /sws/go/register     — Create a new account (public, no auth)
 *   POST /sws/go/login        — Authenticate and get session token (public, no auth)
 *   POST /sws/go/onboarding   — Create a new environment (requires session token, streams NDJSON)
 *   GET  /sws/go/me           — Get current account info (requires session token)
 *   GET  /sws/go/environments — List environments for the account (requires session token)
 *   GET  /sws/go/login?userId=X — Get an Etendo JWT for an AD_User (requires session token + ownership)
 *
 * Auth model: session token in Authorization header ("Bearer <token>").
 * This is independent of Etendo's JWT auth — it uses ETGO_ACCOUNT.SESSION_TOKEN.
 *
 * Database access uses raw JDBC because the DAL entity class for ETGO_ACCOUNT
 * is generated by smartbuild and may not be available at compile time.
 */
public class EtendoGoJwtServlet extends HttpBaseServlet {

  private static final Logger log = LogManager.getLogger(EtendoGoJwtServlet.class);

  private static final String HASH_ALGORITHM = "SHA-256";
  private static final int SALT_BYTES = 16;
  private static final String UTF_8 = "UTF-8";
  private static final String FIELD_EMAIL = "email";
  private static final String FIELD_CLIENT_NAME = "clientName";
  private static final String FIELD_STATUS = "status";
  private static final String FIELD_TOKEN = "token";
  private static final String FIELD_MESSAGE = "message";
  private static final String FIELD_SUCCESS = "success";
  private static final String STATUS_SUCCESS = "success";
  private static final String INVALID_JSON_BODY = "Invalid JSON body";
  private static final String INTERNAL_ERROR = "Internal error";
  private static final String SERVER_ERROR = "Server error";
  private static final String INVALID_AUTHORIZATION_HEADER =
      "Missing or invalid Authorization header";
  private static final String INVALID_OR_EXPIRED_TOKEN = "Invalid or expired token";
  private static final String DB_ACCOUNT_ID = "etgo_account_id";
  private static final String DB_CLIENT_ID = "ad_client_id";
  private static final String DB_ORG_ID = "ad_org_id";
  private static final String PROGRESS_IN_PROGRESS = "in_progress";
  private static final String PROGRESS_CLIENT = "client";
  private static final String PROGRESS_ERROR = "error";
  private static final String PROGRESS_ORGANIZATION = "organization";

  // --- SQL constants ---

  private static final String SQL_FIND_ACCOUNT_BY_EMAIL =
      "SELECT etgo_account_id, email, name, password_hash, session_token, created "
      + "FROM etgo_account WHERE email = ? AND isactive = 'Y'";

  private static final String SQL_FIND_ACCOUNT_BY_TOKEN =
      "SELECT etgo_account_id, email, name, session_token, created "
      + "FROM etgo_account WHERE session_token = ? AND isactive = 'Y'";

  private static final String SQL_INSERT_ACCOUNT =
      "INSERT INTO etgo_account "
      + "(etgo_account_id, ad_client_id, ad_org_id, isactive, "
      + "created, createdby, updated, updatedby, "
      + "email, password_hash, name, session_token) "
      + "VALUES (get_uuid(), '0', '0', 'Y', now(), '0', now(), '0', ?, ?, ?, ?)";

  private static final String SQL_UPDATE_SESSION_TOKEN =
      "UPDATE etgo_account SET session_token = ?, updated = now() "
      + "WHERE etgo_account_id = ?";

  /**
   * SQL to find environments (AD_Client + admin user) linked to an account.
   * The onboarding creates an AD_User with username = account email (or email+clientname).
   * We find all clients where such a user exists (excluding system client '0').
   */
  private static final String SQL_FIND_ENVIRONMENTS_BY_EMAIL =
      "SELECT c.ad_client_id, c.name AS client_name, "
      + "o.ad_org_id, o.name AS org_name, "
      + "u.ad_user_id, u.username AS admin_user "
      + "FROM ad_user u "
      + "JOIN ad_client c ON u.ad_client_id = c.ad_client_id "
      + "LEFT JOIN ad_org o ON o.ad_client_id = c.ad_client_id AND o.value != '*' "
      + "WHERE (u.username = ? OR u.username LIKE ? ) "
      + "AND c.ad_client_id != '0' "
      + "AND u.isactive = 'Y' AND c.isactive = 'Y' "
      + "ORDER BY c.created";

  // --- CORS ---

  private void setCorsHeaders(HttpServletRequest request, HttpServletResponse response) {
    CorsUtils.apply(request, response, "GET, POST, OPTIONS",
        "Content-Type, Authorization, Accept", null, false);
  }

  @Override
  public void service(HttpServletRequest request, HttpServletResponse response)
      throws javax.servlet.ServletException, IOException {
    setCorsHeaders(request, response);
    if ("OPTIONS".equalsIgnoreCase(request.getMethod())) {
      response.setStatus(HttpServletResponse.SC_NO_CONTENT);
      return;
    }
    super.service(request, response);
  }

  // --- HTTP method dispatchers ---

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
    String path = request.getPathInfo();
    if ("/me".equals(path) || "/me/".equals(path)) {
      handleMe(request, response);
    } else if ("/environments".equals(path) || "/environments/".equals(path)) {
      handleEnvironments(request, response);
    } else if ("/login".equals(path) || "/login/".equals(path)) {
      handleEnvironmentLogin(request, response);
    } else {
      writeError(response, HttpServletResponse.SC_NOT_FOUND, "Unknown endpoint: " + path);
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
    String path = request.getPathInfo();
    if ("/register".equals(path) || "/register/".equals(path)) {
      handleRegister(request, response);
    } else if ("/login".equals(path) || "/login/".equals(path)) {
      handleLogin(request, response);
    } else if ("/onboarding".equals(path) || "/onboarding/".equals(path)) {
      handleOnboarding(request, response);
    } else {
      writeError(response, HttpServletResponse.SC_NOT_FOUND, "Unknown endpoint: " + path);
    }
  }

  // --- Endpoint handlers ---

  /**
   * POST /sws/go/register
   * Body: { "email": "...", "password": "...", "name": "..." }
   * Returns 201 with session token on success, 400 if email is taken.
   */
  private void handleRegister(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    JSONObject body;
    try {
      body = readJsonBody(request);
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST, INVALID_JSON_BODY);
      return;
    }

    String email;
    String password;
    String name;
    try {
      email = body.getString(FIELD_EMAIL).trim().toLowerCase();
      password = body.getString("password");
      name = body.getString("name").trim();
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST,
          "Missing required fields: email, password, name");
      return;
    }

    if (email.isEmpty() || password.isEmpty() || name.isEmpty()) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST,
          "Fields email, password, and name must not be empty");
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      // Check if email already exists
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_EMAIL)) {
        ps.setString(1, email);
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) {
            writeError(response, HttpServletResponse.SC_BAD_REQUEST, "Email already registered");
            return;
          }
        }
      }

      // Hash password and generate session token
      String passwordHash = hashPassword(password);
      String sessionToken = generateToken();

      // Insert account
      try (PreparedStatement ps = conn.prepareStatement(SQL_INSERT_ACCOUNT)) {
        ps.setString(1, email);
        ps.setString(2, passwordHash);
        ps.setString(3, name);
        ps.setString(4, sessionToken);
        ps.executeUpdate();
      }
      conn.commit();

      // Fetch the created account to get its ID
      String accountId = null;
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_EMAIL)) {
        ps.setString(1, email);
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) {
            accountId = rs.getString(DB_ACCOUNT_ID);
          }
        }
      }

      JSONObject accountJson = new JSONObject();
      accountJson.put("id", accountId);
      accountJson.put(FIELD_EMAIL, email);
      accountJson.put("name", name);

      JSONObject result = new JSONObject();
      result.put(FIELD_STATUS, STATUS_SUCCESS);
      result.put(FIELD_TOKEN, sessionToken);
      result.put("account", accountJson);

      writeResponse(response, HttpServletResponse.SC_CREATED, result);

    } catch (SQLException e) {
      log.error("Database error during account registration", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
          "Registration failed due to a server error");
    } catch (JSONException e) {
      log.error("JSON error building register response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, INTERNAL_ERROR);
    }
  }

  /**
   * POST /sws/go/login
   * Body: { "email": "...", "password": "..." }
   * Returns 200 with new session token on success, 401 on invalid credentials.
   */
  private void handleLogin(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    JSONObject body;
    try {
      body = readJsonBody(request);
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST, INVALID_JSON_BODY);
      return;
    }

    String email;
    String password;
    try {
      email = body.getString(FIELD_EMAIL).trim().toLowerCase();
      password = body.getString("password");
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST,
          "Missing required fields: email, password");
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      String accountId = null;
      String storedHash = null;
      String accountName = null;

      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_EMAIL)) {
        ps.setString(1, email);
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) {
            accountId = rs.getString(DB_ACCOUNT_ID);
            storedHash = rs.getString("password_hash");
            accountName = rs.getString("name");
          }
        }
      }

      if (accountId == null || !verifyPassword(password, storedHash)) {
        writeError(response, HttpServletResponse.SC_UNAUTHORIZED, "Invalid credentials");
        return;
      }

      // Rotate session token on login
      String sessionToken = generateToken();
      try (PreparedStatement ps = conn.prepareStatement(SQL_UPDATE_SESSION_TOKEN)) {
        ps.setString(1, sessionToken);
        ps.setString(2, accountId);
        ps.executeUpdate();
      }
      conn.commit();

      JSONObject accountJson = new JSONObject();
      accountJson.put("id", accountId);
      accountJson.put(FIELD_EMAIL, email);
      accountJson.put("name", accountName);

      JSONObject result = new JSONObject();
      result.put(FIELD_STATUS, STATUS_SUCCESS);
      result.put(FIELD_TOKEN, sessionToken);
      result.put("account", accountJson);

      writeResponse(response, HttpServletResponse.SC_OK, result);

    } catch (SQLException e) {
      log.error("Database error during login", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
          "Login failed due to a server error");
    } catch (JSONException e) {
      log.error("JSON error building login response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, INTERNAL_ERROR);
    }
  }

  /**
   * GET /sws/go/me
   * Header: Authorization: Bearer <session_token>
   * Returns 200 with account info, 401 if token is invalid.
   */
  private void handleMe(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    String token = extractBearerToken(request);
    if (token == null) {
      writeError(response, HttpServletResponse.SC_UNAUTHORIZED,
          INVALID_AUTHORIZATION_HEADER);
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_TOKEN)) {
        ps.setString(1, token);
        try (ResultSet rs = ps.executeQuery()) {
          if (!rs.next()) {
            writeError(response, HttpServletResponse.SC_UNAUTHORIZED, INVALID_OR_EXPIRED_TOKEN);
            return;
          }

          JSONObject result = new JSONObject();
          result.put("id", rs.getString(DB_ACCOUNT_ID));
          result.put(FIELD_EMAIL, rs.getString(FIELD_EMAIL));
          result.put("name", rs.getString("name"));
          Timestamp created = rs.getTimestamp("created");
          if (created != null) {
            result.put("created", created.toInstant().toString());
          }

          writeResponse(response, HttpServletResponse.SC_OK, result);
        }
      }
    } catch (SQLException e) {
      log.error("Database error fetching account by token", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, SERVER_ERROR);
    } catch (JSONException e) {
      log.error("JSON error building /me response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, INTERNAL_ERROR);
    }
  }

  /**
   * GET /sws/go/environments
   * Header: Authorization: Bearer <session_token>
   * Returns 200 with environments linked to the account.
   * Links via AD_User.username matching the account email.
   */
  private void handleEnvironments(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    String token = extractBearerToken(request);
    if (token == null) {
      writeError(response, HttpServletResponse.SC_UNAUTHORIZED,
          INVALID_AUTHORIZATION_HEADER);
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      // Verify token and get account email
      String accountEmail = null;
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_TOKEN)) {
        ps.setString(1, token);
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) {
            accountEmail = rs.getString(FIELD_EMAIL);
          }
        }
      }

      if (accountEmail == null) {
        writeError(response, HttpServletResponse.SC_UNAUTHORIZED, INVALID_OR_EXPIRED_TOKEN);
        return;
      }

      // Find environments linked to this account via AD_User.username
      org.codehaus.jettison.json.JSONArray envArray = new org.codehaus.jettison.json.JSONArray();
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ENVIRONMENTS_BY_EMAIL)) {
        ps.setString(1, accountEmail);
        ps.setString(2, accountEmail + "+%");
        try (ResultSet rs = ps.executeQuery()) {
          while (rs.next()) {
            JSONObject env = new JSONObject();
            env.put("clientId", rs.getString(DB_CLIENT_ID));
            env.put(FIELD_CLIENT_NAME, rs.getString("client_name"));
            env.put("orgId", rs.getString(DB_ORG_ID));
            env.put("orgName", rs.getString("org_name"));
            env.put("adminUserId", rs.getString("ad_user_id"));
            env.put("adminUser", rs.getString("admin_user"));
            envArray.put(env);
          }
        }
      }

      JSONObject result = new JSONObject();
      result.put("environments", envArray);
      writeResponse(response, HttpServletResponse.SC_OK, result);

    } catch (SQLException e) {
      log.error("Database error in /environments", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, SERVER_ERROR);
    } catch (JSONException e) {
      log.error("JSON error building /environments response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, INTERNAL_ERROR);
    }
  }

  /**
   * GET /sws/go/login?userId={adUserId}
   * Header: Authorization: Bearer <session_token>
   * Returns an Etendo JWT for the given AD_User, if it belongs to the account.
   */
  private void handleEnvironmentLogin(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    String token = extractBearerToken(request);
    if (token == null) {
      writeError(response, HttpServletResponse.SC_UNAUTHORIZED,
          INVALID_AUTHORIZATION_HEADER);
      return;
    }

    String userId = request.getParameter("userId");
    if (userId == null || userId.isEmpty()) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST, "Missing userId parameter");
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      String accountEmail = EtendoGoJwtSupport.requireAccountEmail(conn, token);
      if (accountEmail == null) {
        writeError(response, HttpServletResponse.SC_UNAUTHORIZED, INVALID_OR_EXPIRED_TOKEN);
        return;
      }

      if (!EtendoGoJwtSupport.isEnvironmentUserOwnedByAccount(conn, accountEmail, userId)) {
        writeError(response, HttpServletResponse.SC_FORBIDDEN,
            "User does not belong to this account");
        return;
      }

        EtendoGoJwtSupport.RoleListData roleListData =
          EtendoGoJwtSupport.loadRoleListData(conn, userId);
      writeEnvironmentLoginResponse(response, userId, roleListData);

    } catch (SQLException e) {
      log.error("Database error in /login", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, SERVER_ERROR);
    } catch (JSONException e) {
      log.error("JSON error in /login", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, INTERNAL_ERROR);
    } catch (Exception e) {
      log.error("Token generation error in /login", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Token generation failed");
    }
  }

  // --- Onboarding ---

  /**
   * SQL to resolve a currency ID from its ISO code (e.g. "EUR" → "102").
   */
  private static final String SQL_FIND_CURRENCY_BY_ISO =
      "SELECT c_currency_id FROM c_currency WHERE iso_code = ?";

  /**
   * SQL to find the admin role and user created by InitialClientSetup for a client.
   */
  private static final String SQL_FIND_CLIENT_ADMIN =
      "SELECT r.ad_role_id, u.ad_user_id "
      + "FROM ad_role r "
      + "JOIN ad_user_roles ur ON ur.ad_role_id = r.ad_role_id "
      + "JOIN ad_user u ON ur.ad_user_id = u.ad_user_id "
      + "WHERE r.ad_client_id = ? AND u.ad_user_id != '100' "
      + "ORDER BY r.created LIMIT 1";

  /**
   * POST /sws/go/onboarding
   * Header: Authorization: Bearer <session_token>
   * Body: { "clientName": "...", "currency": "EUR", "language": "es_ES", "countryCode": "ES" }
   *
   * Creates a new Etendo environment (AD_Client + AD_Org) using the existing
   * InitialClientSetup and InitialOrgSetup business utilities.
   *
   * Streams NDJSON progress lines to the frontend.
   */
  private void handleOnboarding(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    String token = extractBearerToken(request);
    if (token == null) {
      writeError(response, HttpServletResponse.SC_UNAUTHORIZED,
          INVALID_AUTHORIZATION_HEADER);
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    final String accountEmail;
    try {
      accountEmail = EtendoGoJwtSupport.requireAccountEmail(conn, token);
      if (accountEmail == null) {
        writeError(response, HttpServletResponse.SC_UNAUTHORIZED, INVALID_OR_EXPIRED_TOKEN);
        return;
      }
    } catch (SQLException e) {
      log.error("Database error validating token for onboarding", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, SERVER_ERROR);
      return;
    }

    OnboardingRequestData onboardingRequest = parseOnboardingRequest(request, response);
    if (onboardingRequest == null) {
      return;
    }

    final String currencyId;
    try {
      currencyId = resolveCurrencyId(conn, onboardingRequest.currencyIso, response);
    } catch (SQLException e) {
      log.error("Error resolving currency ISO: {}", onboardingRequest.currencyIso, e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, SERVER_ERROR);
      return;
    }
    if (currencyId == null) {
      return;
    }

    // Set up NDJSON streaming
    response.setStatus(HttpServletResponse.SC_OK);
    response.setContentType("application/x-ndjson");
    response.setCharacterEncoding(UTF_8);
    response.setHeader("X-Content-Type-Options", "nosniff");
    PrintWriter writer = response.getWriter();

    // Generate a random password for the admin user
    String adminPassword = UUID.randomUUID().toString().substring(0, 12);

    try {
      VariablesSecureApp vars = prepareAdminContext(writer, onboardingRequest.language);
      String clientId = resolveOrCreateClient(conn, writer, vars, accountEmail, onboardingRequest,
          currencyId, adminPassword);
      if (clientId == null) {
        return;
      }

      conn = OBDal.getInstance().getConnection();
      AdminContextData adminContext = resolveAdminContextData(conn, clientId, writer);
      if (adminContext == null) {
        return;
      }

      if (!ensureOrganization(conn, writer, onboardingRequest.clientName, clientId, adminContext,
          currencyId)) {
        return;
      }

      sendProgress(writer, "finalize", PROGRESS_IN_PROGRESS, "Finalizing setup...");
      sendProgress(writer, "finalize", "done", "Environment ready");
      sendFinalResult(writer, true, "Environment created successfully");

    } catch (Exception e) {
      log.error("Onboarding failed", e);
      try {
        OBDal.getInstance().rollbackAndClose();
      } catch (Exception rollbackEx) {
        log.error("Rollback failed", rollbackEx);
      }
      sendProgress(writer, PROGRESS_ERROR, PROGRESS_ERROR,
          "Onboarding failed: " + e.getMessage());
      sendFinalResult(writer, false, "Onboarding failed: " + e.getMessage());
    } finally {
      OBContext.restorePreviousMode();
      writer.flush();
    }
  }

  private void writeEnvironmentLoginResponse(HttpServletResponse response, String userId,
      EtendoGoJwtSupport.RoleListData roleListData) throws Exception {
    OBContext.setOBContext("0", "0", "0", "0");
    OBContext.setAdminMode(true);
    try {
      User user = OBDal.getInstance().get(User.class, userId);
      if (user == null) {
        writeError(response, HttpServletResponse.SC_NOT_FOUND, "User not found");
        return;
      }
      Role role = roleListData.firstRoleId != null
          ? OBDal.getInstance().get(Role.class, roleListData.firstRoleId)
          : null;
      String jwtToken = SecureWebServicesUtils.generateToken(user, role);

      JSONObject result = new JSONObject();
      result.put(FIELD_TOKEN, jwtToken);
      result.put("roleList", roleListData.roleArray);
      writeResponse(response, HttpServletResponse.SC_OK, result);
    } finally {
      OBContext.restorePreviousMode();
    }
  }

  private OnboardingRequestData parseOnboardingRequest(HttpServletRequest request,
      HttpServletResponse response) throws IOException {
    try {
      JSONObject body = readJsonBody(request);
      String clientName = body.getString(FIELD_CLIENT_NAME).trim();
      if (clientName.isEmpty()) {
        writeError(response, HttpServletResponse.SC_BAD_REQUEST,
        FIELD_CLIENT_NAME + " must not be empty");
        return null;
      }
      OnboardingRequestData data = new OnboardingRequestData();
      data.clientName = clientName;
      data.currencyIso = body.optString("currency", "EUR").trim();
      data.language = body.optString("language", "en_US").trim();
      return data;
    } catch (JSONException e) {
        String message = e.getMessage() != null && e.getMessage().contains(FIELD_CLIENT_NAME)
          ? "Missing required field: " + FIELD_CLIENT_NAME
          : INVALID_JSON_BODY;
      writeError(response, HttpServletResponse.SC_BAD_REQUEST, message);
      return null;
    }
  }

  private String resolveCurrencyId(Connection conn, String currencyIso,
      HttpServletResponse response) throws SQLException, IOException {
    try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_CURRENCY_BY_ISO)) {
      ps.setString(1, currencyIso.toUpperCase());
      try (ResultSet rs = ps.executeQuery()) {
        if (rs.next()) {
          return rs.getString("c_currency_id");
        }
      }
    }
    writeError(response, HttpServletResponse.SC_BAD_REQUEST, "Unknown currency: " + currencyIso);
    return null;
  }

  private VariablesSecureApp prepareAdminContext(PrintWriter writer, String language) {
    sendProgress(writer, "setup", PROGRESS_IN_PROGRESS, "Setting up admin context...");
    OBContext.setOBContext("0", "0", "0", "0");
    OBContext.setAdminMode(true);
    VariablesSecureApp vars = new VariablesSecureApp("0", "0", "0", "0", language);
    sendProgress(writer, "setup", "done", "Admin context ready");
    return vars;
  }

  private String resolveOrCreateClient(Connection conn, PrintWriter writer, VariablesSecureApp vars,
      String accountEmail, OnboardingRequestData requestData, String currencyId,
      String adminPassword) throws Exception {
    sendProgress(writer, PROGRESS_CLIENT, PROGRESS_IN_PROGRESS,
        "Creating client: " + requestData.clientName + "...");
    String clientId = EtendoGoJwtSupport.findClientIdByName(conn, requestData.clientName);
    if (clientId != null) {
      return validateExistingClient(conn, writer, requestData.clientName, clientId) ? clientId : null;
    }

    String clientUser = EtendoGoJwtSupport.buildClientUsername(conn, accountEmail,
        requestData.clientName);
    if (!createClient(vars, currencyId, requestData.clientName, clientUser, adminPassword, writer)) {
      return null;
    }
    return EtendoGoJwtSupport.findClientIdByName(OBDal.getInstance().getConnection(),
        requestData.clientName);
  }

  private boolean validateExistingClient(Connection conn, PrintWriter writer, String clientName,
      String clientId) throws SQLException {
    if (!EtendoGoJwtSupport.hasStarOrganization(conn, clientId)) {
      sendProgress(writer, PROGRESS_CLIENT, PROGRESS_ERROR,
          "Client '" + clientName + "' exists but is incomplete. Use a different name.");
      sendFinalResult(writer, false,
          "A previous attempt left '" + clientName + "' in an incomplete state. Please choose a different company name.");
      return false;
    }
    sendProgress(writer, PROGRESS_CLIENT, "done", "Client already exists, resuming...");
    return true;
  }

  private boolean createClient(VariablesSecureApp vars, String currencyId, String clientName,
      String clientUser, String adminPassword, PrintWriter writer) {
    InitialClientSetup clientSetup = new InitialClientSetup();
    OBError clientResult = clientSetup.createClient(vars, currencyId, clientName, clientUser,
        adminPassword, "", "Account", "Calendar", false, null, false, false, false,
        false, false);
    if (!"Success".equals(clientResult.getType())) {
      String errorMsg = clientResult.getMessage() != null
          ? clientResult.getMessage()
          : "Client creation failed";
      sendProgress(writer, PROGRESS_CLIENT, PROGRESS_ERROR, errorMsg);
      sendFinalResult(writer, false, errorMsg);
      return false;
    }
    sendProgress(writer, PROGRESS_CLIENT, "done", "Client created successfully");
    return true;
  }

  private AdminContextData resolveAdminContextData(Connection conn, String clientId,
      PrintWriter writer) throws SQLException {
    AdminContextData data = new AdminContextData();
    try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_CLIENT_ADMIN)) {
      ps.setString(1, clientId);
      try (ResultSet rs = ps.executeQuery()) {
        if (rs.next()) {
          data.adminRoleId = rs.getString("ad_role_id");
          data.adminUserId = rs.getString("ad_user_id");
        }
      }
    }
    if (data.adminRoleId == null || data.adminUserId == null) {
      sendProgress(writer, PROGRESS_ORGANIZATION, PROGRESS_ERROR,
          "Could not find admin role for new client");
      sendFinalResult(writer, false, "Admin role not found — client may be incomplete");
      return null;
    }
    data.starOrgId = EtendoGoJwtSupport.findStarOrgId(conn, clientId);
    OBContext.setOBContext(data.adminUserId, data.adminRoleId, clientId, data.starOrgId);
    OBContext.setAdminMode(true);
    return data;
  }

  private boolean ensureOrganization(Connection conn, PrintWriter writer, String clientName,
      String clientId, AdminContextData adminContext, String currencyId) throws SQLException {
    sendProgress(writer, PROGRESS_ORGANIZATION, PROGRESS_IN_PROGRESS,
        "Creating organization: " + clientName + "...");
    if (EtendoGoJwtSupport.organizationExists(conn, clientId)) {
      sendProgress(writer, PROGRESS_ORGANIZATION, "done",
          "Organization already exists, resuming...");
      return true;
    }
    return createOrganization(writer, clientName, clientId, adminContext.starOrgId, currencyId);
  }

  private boolean createOrganization(PrintWriter writer, String clientName, String clientId,
      String starOrgId, String currencyId) {
    Client client = OBDal.getInstance().get(Client.class, clientId);
    if (client == null) {
      sendProgress(writer, PROGRESS_ORGANIZATION, PROGRESS_ERROR,
          "Could not load client entity");
      sendFinalResult(writer, false, "Client entity not found in DAL");
      return false;
    }
    InitialOrgSetup orgSetup = new InitialOrgSetup(client);
    OBError orgResult = orgSetup.createOrganization(clientName, "", "0", starOrgId, null,
        "", "", false, null, currencyId, false, false, false, false, false);
    if (!"Success".equals(orgResult.getType())) {
      String errorMsg = orgResult.getMessage() != null
          ? orgResult.getMessage()
          : "Organization creation failed";
      sendProgress(writer, PROGRESS_ORGANIZATION, PROGRESS_ERROR, errorMsg);
      sendFinalResult(writer, false, errorMsg);
      return false;
    }
    sendProgress(writer, PROGRESS_ORGANIZATION, "done", "Organization created successfully");
    return true;
  }

  /**
   * Write a NDJSON progress line.
   */
  private void sendProgress(PrintWriter writer, String step, String status, String message) {
    try {
      JSONObject progress = new JSONObject();
      progress.put("type", "progress");
      progress.put("step", step);
      progress.put(FIELD_STATUS, status);
      progress.put(FIELD_MESSAGE, message);
      progress.put("timestamp", Instant.now().toString());
      writer.println(progress.toString());
      writer.flush();
    } catch (JSONException e) {
      log.warn("Error writing progress", e);
    }
  }

  /**
   * Write the final NDJSON result line.
   */
  private void sendFinalResult(PrintWriter writer, boolean success, String message) {
    try {
      JSONObject result = new JSONObject();
      result.put("type", "result");
      result.put(FIELD_SUCCESS, success);
      result.put(FIELD_MESSAGE, message);
      result.put("timestamp", Instant.now().toString());
      writer.println(result.toString());
      writer.flush();
    } catch (JSONException e) {
      log.warn("Error writing final result", e);
    }
  }

  // --- Password utilities ---

  /**
   * Hash a plaintext password using SHA-256 with a random salt.
   * Returns "base64(salt):base64(hash)" so the salt can be recovered for verification.
   */
  private String hashPassword(String password) {
    try {
      SecureRandom random = new SecureRandom();
      byte[] salt = new byte[SALT_BYTES];
      random.nextBytes(salt);

      MessageDigest md = MessageDigest.getInstance(HASH_ALGORITHM);
      md.update(salt);
      byte[] hash = md.digest(password.getBytes(StandardCharsets.UTF_8));

      String saltB64 = Base64.getEncoder().encodeToString(salt);
      String hashB64 = Base64.getEncoder().encodeToString(hash);
      return saltB64 + ":" + hashB64;
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException("SHA-256 not available", e);
    }
  }

  /**
   * Verify a plaintext password against a stored "salt:hash" string.
   * Returns true if the password matches.
   */
  private boolean verifyPassword(String password, String storedHash) {
    if (storedHash == null || !storedHash.contains(":")) {
      return false;
    }
    try {
      String[] parts = storedHash.split(":", 2);
      byte[] salt = Base64.getDecoder().decode(parts[0]);
      byte[] expectedHash = Base64.getDecoder().decode(parts[1]);

      MessageDigest md = MessageDigest.getInstance(HASH_ALGORITHM);
      md.update(salt);
      byte[] actualHash = md.digest(password.getBytes(StandardCharsets.UTF_8));

      // Constant-time comparison to prevent timing attacks
      if (actualHash.length != expectedHash.length) {
        return false;
      }
      int diff = 0;
      for (int i = 0; i < actualHash.length; i++) {
        diff |= actualHash[i] ^ expectedHash[i];
      }
      return diff == 0;
    } catch (NoSuchAlgorithmException | IllegalArgumentException e) {
      log.warn("Password verification failed: {}", e.getMessage());
      return false;
    }
  }

  /**
   * Generate a random URL-safe session token (UUID without hyphens, 32 hex chars).
   */
  private String generateToken() {
    return UUID.randomUUID().toString().replace("-", "").toLowerCase();
  }

  // --- HTTP utilities ---

  /**
   * Extract the Bearer token from the Authorization header.
   * Returns null if the header is absent or malformed.
   */
  private String extractBearerToken(HttpServletRequest request) {
    String authHeader = request.getHeader("Authorization");
    if (authHeader == null || !authHeader.startsWith("Bearer ")) {
      return null;
    }
    String token = authHeader.substring(7).trim();
    return token.isEmpty() ? null : token;
  }

  /**
   * Read and parse the request body as a JSONObject.
   */
  private JSONObject readJsonBody(HttpServletRequest request)
      throws IOException, JSONException {
    StringBuilder sb = new StringBuilder();
    try (BufferedReader reader = request.getReader()) {
      String line;
      while ((line = reader.readLine()) != null) {
        sb.append(line);
      }
    }
    return new JSONObject(sb.toString());
  }

  /**
   * Write a JSON response with the given HTTP status code.
   */
  private void writeResponse(HttpServletResponse response, int status, JSONObject body)
      throws IOException {
    response.setStatus(status);
    response.setContentType("application/json");
    response.setCharacterEncoding(UTF_8);
    try (PrintWriter writer = response.getWriter()) {
      writer.write(body.toString());
    }
  }

  /**
   * Write a JSON error response: { "error": { "message": "...", "status": N } }
   */
  private void writeError(HttpServletResponse response, int status, String message)
      throws IOException {
    response.setStatus(status);
    response.setContentType("application/json");
    response.setCharacterEncoding(UTF_8);
    try (PrintWriter writer = response.getWriter()) {
      try {
        JSONObject error = new JSONObject();
        error.put(FIELD_MESSAGE, message);
        error.put(FIELD_STATUS, status);

        JSONObject wrapper = new JSONObject();
        wrapper.put(PROGRESS_ERROR, error);

        writer.write(wrapper.toString());
      } catch (JSONException e) {
        // Fallback to plain text if JSON construction fails
        writer.write("{\"error\":{\"message\":\"" + message + "\",\"status\":" + status + "}}");
      }
    }
  }

  private static class OnboardingRequestData {
    private String clientName;
    private String currencyIso;
    private String language;
  }

  private static class AdminContextData {
    private String adminRoleId;
    private String adminUserId;
    private String starOrgId;
  }
}
