package com.etendoerp.go.rest;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Base64;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;
import org.openbravo.base.HttpBaseServlet;
import org.openbravo.dal.service.OBDal;

/**
 * EtendoGo JWT Servlet — account management for platform users.
 *
 * Mapped to /sws/go/* via AD_MODEL_OBJECT_MAPPING (ID: FB313FD86E7846F8992F4C61B7230066).
 *
 * Endpoints:
 *   POST /sws/go/register     — Create a new account (public, no auth)
 *   POST /sws/go/login        — Authenticate and get session token (public, no auth)
 *   GET  /sws/go/me           — Get current account info (requires session token)
 *   GET  /sws/go/environments — List environments for the account (requires session token)
 *
 * Auth model: session token in Authorization header ("Bearer <token>").
 * This is independent of Etendo's JWT auth — it uses ETGO_ACCOUNT.SESSION_TOKEN.
 *
 * Database access uses raw JDBC because the DAL entity class for ETGO_ACCOUNT
 * is generated by smartbuild and may not be available at compile time.
 */
public class EtendoGoJwtServlet extends HttpBaseServlet {

  private static final Logger log = LogManager.getLogger(EtendoGoJwtServlet.class);

  private static final String HASH_ALGORITHM = "SHA-256";
  private static final int SALT_BYTES = 16;

  // --- SQL constants ---

  private static final String SQL_FIND_ACCOUNT_BY_EMAIL =
      "SELECT etgo_account_id, email, name, password_hash, session_token, created "
      + "FROM etgo_account WHERE email = ? AND isactive = 'Y'";

  private static final String SQL_FIND_ACCOUNT_BY_TOKEN =
      "SELECT etgo_account_id, email, name, session_token, created "
      + "FROM etgo_account WHERE session_token = ? AND isactive = 'Y'";

  private static final String SQL_INSERT_ACCOUNT =
      "INSERT INTO etgo_account "
      + "(etgo_account_id, ad_client_id, ad_org_id, isactive, "
      + "created, createdby, updated, updatedby, "
      + "email, password_hash, name, session_token) "
      + "VALUES (get_uuid(), '0', '0', 'Y', now(), '0', now(), '0', ?, ?, ?, ?)";

  private static final String SQL_UPDATE_SESSION_TOKEN =
      "UPDATE etgo_account SET session_token = ?, updated = now() "
      + "WHERE etgo_account_id = ?";

  // --- CORS ---

  private void setCorsHeaders(HttpServletResponse response) {
    response.setHeader("Access-Control-Allow-Origin", "*");
    response.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    response.setHeader("Access-Control-Allow-Headers",
        "Content-Type, Authorization, Accept");
    response.setHeader("Access-Control-Max-Age", "86400");
  }

  @Override
  public void service(HttpServletRequest request, HttpServletResponse response)
      throws javax.servlet.ServletException, IOException {
    setCorsHeaders(response);
    if ("OPTIONS".equalsIgnoreCase(request.getMethod())) {
      response.setStatus(HttpServletResponse.SC_NO_CONTENT);
      return;
    }
    super.service(request, response);
  }

  // --- HTTP method dispatchers ---

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
    String path = request.getPathInfo();
    if ("/me".equals(path) || "/me/".equals(path)) {
      handleMe(request, response);
    } else if ("/environments".equals(path) || "/environments/".equals(path)) {
      handleEnvironments(request, response);
    } else {
      writeError(response, HttpServletResponse.SC_NOT_FOUND, "Unknown endpoint: " + path);
    }
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
    String path = request.getPathInfo();
    if ("/register".equals(path) || "/register/".equals(path)) {
      handleRegister(request, response);
    } else if ("/login".equals(path) || "/login/".equals(path)) {
      handleLogin(request, response);
    } else {
      writeError(response, HttpServletResponse.SC_NOT_FOUND, "Unknown endpoint: " + path);
    }
  }

  // --- Endpoint handlers ---

  /**
   * POST /sws/go/register
   * Body: { "email": "...", "password": "...", "name": "..." }
   * Returns 201 with session token on success, 400 if email is taken.
   */
  private void handleRegister(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    JSONObject body;
    try {
      body = readJsonBody(request);
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST, "Invalid JSON body");
      return;
    }

    String email;
    String password;
    String name;
    try {
      email = body.getString("email").trim().toLowerCase();
      password = body.getString("password");
      name = body.getString("name").trim();
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST,
          "Missing required fields: email, password, name");
      return;
    }

    if (email.isEmpty() || password.isEmpty() || name.isEmpty()) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST,
          "Fields email, password, and name must not be empty");
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      // Check if email already exists
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_EMAIL)) {
        ps.setString(1, email);
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) {
            writeError(response, HttpServletResponse.SC_BAD_REQUEST, "Email already registered");
            return;
          }
        }
      }

      // Hash password and generate session token
      String passwordHash = hashPassword(password);
      String sessionToken = generateToken();

      // Insert account
      try (PreparedStatement ps = conn.prepareStatement(SQL_INSERT_ACCOUNT)) {
        ps.setString(1, email);
        ps.setString(2, passwordHash);
        ps.setString(3, name);
        ps.setString(4, sessionToken);
        ps.executeUpdate();
      }
      conn.commit();

      // Fetch the created account to get its ID
      String accountId = null;
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_EMAIL)) {
        ps.setString(1, email);
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) {
            accountId = rs.getString("etgo_account_id");
          }
        }
      }

      JSONObject accountJson = new JSONObject();
      accountJson.put("id", accountId);
      accountJson.put("email", email);
      accountJson.put("name", name);

      JSONObject result = new JSONObject();
      result.put("status", "success");
      result.put("token", sessionToken);
      result.put("account", accountJson);

      writeResponse(response, HttpServletResponse.SC_CREATED, result);

    } catch (SQLException e) {
      log.error("Database error during account registration", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
          "Registration failed due to a server error");
    } catch (JSONException e) {
      log.error("JSON error building register response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Internal error");
    }
  }

  /**
   * POST /sws/go/login
   * Body: { "email": "...", "password": "..." }
   * Returns 200 with new session token on success, 401 on invalid credentials.
   */
  private void handleLogin(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    JSONObject body;
    try {
      body = readJsonBody(request);
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST, "Invalid JSON body");
      return;
    }

    String email;
    String password;
    try {
      email = body.getString("email").trim().toLowerCase();
      password = body.getString("password");
    } catch (JSONException e) {
      writeError(response, HttpServletResponse.SC_BAD_REQUEST,
          "Missing required fields: email, password");
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      String accountId = null;
      String storedHash = null;
      String accountName = null;

      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_EMAIL)) {
        ps.setString(1, email);
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) {
            accountId = rs.getString("etgo_account_id");
            storedHash = rs.getString("password_hash");
            accountName = rs.getString("name");
          }
        }
      }

      if (accountId == null || !verifyPassword(password, storedHash)) {
        writeError(response, HttpServletResponse.SC_UNAUTHORIZED, "Invalid credentials");
        return;
      }

      // Rotate session token on login
      String sessionToken = generateToken();
      try (PreparedStatement ps = conn.prepareStatement(SQL_UPDATE_SESSION_TOKEN)) {
        ps.setString(1, sessionToken);
        ps.setString(2, accountId);
        ps.executeUpdate();
      }
      conn.commit();

      JSONObject accountJson = new JSONObject();
      accountJson.put("id", accountId);
      accountJson.put("email", email);
      accountJson.put("name", accountName);

      JSONObject result = new JSONObject();
      result.put("status", "success");
      result.put("token", sessionToken);
      result.put("account", accountJson);

      writeResponse(response, HttpServletResponse.SC_OK, result);

    } catch (SQLException e) {
      log.error("Database error during login", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
          "Login failed due to a server error");
    } catch (JSONException e) {
      log.error("JSON error building login response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Internal error");
    }
  }

  /**
   * GET /sws/go/me
   * Header: Authorization: Bearer <session_token>
   * Returns 200 with account info, 401 if token is invalid.
   */
  private void handleMe(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    String token = extractBearerToken(request);
    if (token == null) {
      writeError(response, HttpServletResponse.SC_UNAUTHORIZED,
          "Missing or invalid Authorization header");
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_TOKEN)) {
        ps.setString(1, token);
        try (ResultSet rs = ps.executeQuery()) {
          if (!rs.next()) {
            writeError(response, HttpServletResponse.SC_UNAUTHORIZED, "Invalid or expired token");
            return;
          }

          JSONObject result = new JSONObject();
          result.put("id", rs.getString("etgo_account_id"));
          result.put("email", rs.getString("email"));
          result.put("name", rs.getString("name"));
          Timestamp created = rs.getTimestamp("created");
          if (created != null) {
            result.put("created", created.toInstant().toString());
          }

          writeResponse(response, HttpServletResponse.SC_OK, result);
        }
      }
    } catch (SQLException e) {
      log.error("Database error fetching account by token", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Server error");
    } catch (JSONException e) {
      log.error("JSON error building /me response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Internal error");
    }
  }

  /**
   * GET /sws/go/environments
   * Header: Authorization: Bearer <session_token>
   * Returns 200 with environments list. Currently always returns empty array.
   * Future: query AD_Client records linked to this account.
   */
  private void handleEnvironments(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    String token = extractBearerToken(request);
    if (token == null) {
      writeError(response, HttpServletResponse.SC_UNAUTHORIZED,
          "Missing or invalid Authorization header");
      return;
    }

    Connection conn = OBDal.getInstance().getConnection();
    try {
      // Verify token is valid
      boolean valid = false;
      try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_ACCOUNT_BY_TOKEN)) {
        ps.setString(1, token);
        try (ResultSet rs = ps.executeQuery()) {
          valid = rs.next();
        }
      }

      if (!valid) {
        writeError(response, HttpServletResponse.SC_UNAUTHORIZED, "Invalid or expired token");
        return;
      }

      JSONObject result = new JSONObject();
      result.put("environments", new org.codehaus.jettison.json.JSONArray());

      writeResponse(response, HttpServletResponse.SC_OK, result);

    } catch (SQLException e) {
      log.error("Database error in /environments", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Server error");
    } catch (JSONException e) {
      log.error("JSON error building /environments response", e);
      writeError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Internal error");
    }
  }

  // --- Password utilities ---

  /**
   * Hash a plaintext password using SHA-256 with a random salt.
   * Returns "base64(salt):base64(hash)" so the salt can be recovered for verification.
   */
  private String hashPassword(String password) {
    try {
      SecureRandom random = new SecureRandom();
      byte[] salt = new byte[SALT_BYTES];
      random.nextBytes(salt);

      MessageDigest md = MessageDigest.getInstance(HASH_ALGORITHM);
      md.update(salt);
      byte[] hash = md.digest(password.getBytes(StandardCharsets.UTF_8));

      String saltB64 = Base64.getEncoder().encodeToString(salt);
      String hashB64 = Base64.getEncoder().encodeToString(hash);
      return saltB64 + ":" + hashB64;
    } catch (NoSuchAlgorithmException e) {
      throw new RuntimeException("SHA-256 not available", e);
    }
  }

  /**
   * Verify a plaintext password against a stored "salt:hash" string.
   * Returns true if the password matches.
   */
  private boolean verifyPassword(String password, String storedHash) {
    if (storedHash == null || !storedHash.contains(":")) {
      return false;
    }
    try {
      String[] parts = storedHash.split(":", 2);
      byte[] salt = Base64.getDecoder().decode(parts[0]);
      byte[] expectedHash = Base64.getDecoder().decode(parts[1]);

      MessageDigest md = MessageDigest.getInstance(HASH_ALGORITHM);
      md.update(salt);
      byte[] actualHash = md.digest(password.getBytes(StandardCharsets.UTF_8));

      // Constant-time comparison to prevent timing attacks
      if (actualHash.length != expectedHash.length) {
        return false;
      }
      int diff = 0;
      for (int i = 0; i < actualHash.length; i++) {
        diff |= actualHash[i] ^ expectedHash[i];
      }
      return diff == 0;
    } catch (NoSuchAlgorithmException | IllegalArgumentException e) {
      log.warn("Password verification failed: {}", e.getMessage());
      return false;
    }
  }

  /**
   * Generate a random URL-safe session token (UUID without hyphens, 32 hex chars).
   */
  private String generateToken() {
    return UUID.randomUUID().toString().replace("-", "").toLowerCase();
  }

  // --- HTTP utilities ---

  /**
   * Extract the Bearer token from the Authorization header.
   * Returns null if the header is absent or malformed.
   */
  private String extractBearerToken(HttpServletRequest request) {
    String authHeader = request.getHeader("Authorization");
    if (authHeader == null || !authHeader.startsWith("Bearer ")) {
      return null;
    }
    String token = authHeader.substring(7).trim();
    return token.isEmpty() ? null : token;
  }

  /**
   * Read and parse the request body as a JSONObject.
   */
  private JSONObject readJsonBody(HttpServletRequest request)
      throws IOException, JSONException {
    StringBuilder sb = new StringBuilder();
    try (BufferedReader reader = request.getReader()) {
      String line;
      while ((line = reader.readLine()) != null) {
        sb.append(line);
      }
    }
    return new JSONObject(sb.toString());
  }

  /**
   * Write a JSON response with the given HTTP status code.
   */
  private void writeResponse(HttpServletResponse response, int status, JSONObject body)
      throws IOException {
    response.setStatus(status);
    response.setContentType("application/json");
    response.setCharacterEncoding("UTF-8");
    try (PrintWriter writer = response.getWriter()) {
      writer.write(body.toString());
    }
  }

  /**
   * Write a JSON error response: { "error": { "message": "...", "status": N } }
   */
  private void writeError(HttpServletResponse response, int status, String message)
      throws IOException {
    response.setStatus(status);
    response.setContentType("application/json");
    response.setCharacterEncoding("UTF-8");
    try (PrintWriter writer = response.getWriter()) {
      try {
        JSONObject error = new JSONObject();
        error.put("message", message);
        error.put("status", status);

        JSONObject wrapper = new JSONObject();
        wrapper.put("error", error);

        writer.write(wrapper.toString());
      } catch (JSONException e) {
        // Fallback to plain text if JSON construction fails
        writer.write("{\"error\":{\"message\":\"" + message + "\",\"status\":" + status + "}}");
      }
    }
  }
}
