// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.validation;

import java.util.ArrayList;
import java.util.List;
import org.openbravo.base.exception.OBException;
import ;

/**
 * Precondition Validator: AddPaymentValidator
 *
 * Validates entity state before process execution.
 * Collects all validation errors before throwing.
 */
public class AddPaymentValidator {

  /**
   * Validate all preconditions for the given entity.
   *
   * @param order the entity to validate
   * @throws OBException if any precondition fails
   */
  public void validate(Object order) {
    final List<String> errors = new ArrayList<>();

    if (order.docStatus &#x3D;&#x3D; &#x27;CO&#x27;) {
      errors.add("Order must be completed before adding a payment");
    }
    if (order.grandTotal &gt; 0) {
      errors.add("Order must have a positive grand total");
    }
    if (order.businessPartner.paymentMethod !&#x3D; null) {
      errors.add("Business partner must have a payment method configured");
    }

    if (!errors.isEmpty()) {
      throw new OBException(String.join("; ", errors));
    }
  }
}
