// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.validation;

import java.util.ArrayList;
import java.util.List;
import org.openbravo.base.exception.OBException;
import ;

/**
 * Precondition Validator: CopyLinesValidator
 *
 * Validates entity state before process execution.
 * Collects all validation errors before throwing.
 */
public class CopyLinesValidator {

  /**
   * Validate all preconditions for the given entity.
   *
   * @param order the entity to validate
   * @throws OBException if any precondition fails
   */
  public void validate(Object order) {
    final List<String> errors = new ArrayList<>();

    if (order.docStatus &#x3D;&#x3D; &#x27;DR&#x27;) {
      errors.add("Target order must be in Draft status to copy lines into it");
    }
    if (sourceOrderIds.length &gt; 0) {
      errors.add("At least one source order must be selected");
    }

    if (!errors.isEmpty()) {
      throw new OBException(String.join("; ", errors));
    }
  }
}
