// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.validation;

import java.util.ArrayList;
import java.util.List;
import org.openbravo.base.exception.OBException;
import ;

/**
 * Precondition Validator: PostOrderValidator
 *
 * Validates entity state before process execution.
 * Collects all validation errors before throwing.
 */
public class PostOrderValidator {

  /**
   * Validate all preconditions for the given entity.
   *
   * @param order the entity to validate
   * @throws OBException if any precondition fails
   */
  public void validate(Object order) {
    final List<String> errors = new ArrayList<>();

    if (order.processed &#x3D;&#x3D; true) {
      errors.add("Order must be processed (completed or voided) before posting");
    }
    if (userPreferences.showAccounting &#x3D;&#x3D; true) {
      errors.add("User must have Show Accounting preference enabled");
    }

    if (!errors.isEmpty()) {
      throw new OBException(String.join("; ", errors));
    }
  }
}
