// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.validation;

import java.util.ArrayList;
import java.util.List;
import org.openbravo.base.exception.OBException;
import ;

/**
 * Precondition Validator: ProcessOrderValidator
 *
 * Validates entity state before process execution.
 * Collects all validation errors before throwing.
 */
public class ProcessOrderValidator {

  /**
   * Validate all preconditions for the given entity.
   *
   * @param order the entity to validate
   * @throws OBException if any precondition fails
   */
  public void validate(Object order) {
    final List<String> errors = new ArrayList<>();

    if (order.docStatus IN (&#x27;DR&#x27;, &#x27;IP&#x27;)) {
      errors.add("Order must be in Draft or In Progress status to complete");
    }
    if (order.lines.length &gt; 0) {
      errors.add("Order must have at least one line");
    }
    if (order.businessPartner.currency !&#x3D; null) {
      errors.add("Business partner must have a currency configured before completion");
    }

    if (!errors.isEmpty()) {
      throw new OBException(String.join("; ", errors));
    }
  }
}
