// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Schema version: 
// Checksum: 
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.event;

import javax.enterprise.event.Observes;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;
import org.openbravo.dal.core.OBContext;
import com.etendoerp.go.dto.COrderLineDTO;

/**
 * Event handler for cOrderLine entity derivations.
 *
 * Handles automatic field derivation on create and update events.
 */
public class COrderLineDerivationHandler extends EntityPersistenceEventObserver {

  private static final Entity[] ENTITIES = {
    ModelProvider.getInstance().getEntity(cOrderLine.ENTITY_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return ENTITIES;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(org.openbravo.client.kernel.event.EntityPersistenceEvent event) {
    // Derivation: mWarehouseId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("mWarehouseId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.mWarehouseId);
        }
      } else {
        event.setCurrentState(prop, context.mWarehouseId);
      }
    }
    // Derivation: qtyReserved (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("qtyReserved");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, 0);
        }
      } else {
        event.setCurrentState(prop, 0);
      }
    }
    // Derivation: mShipperId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("mShipperId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.mShipperId);
        }
      } else {
        event.setCurrentState(prop, context.mShipperId);
      }
    }
    // Derivation: cBpartnerId (lookup) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cBpartnerId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, SELECT C_BPartner_ID AS DefaultValue FROM C_Order WHERE C_Order_ID=@C_Order_ID@);
        }
      } else {
        event.setCurrentState(prop, SELECT C_BPartner_ID AS DefaultValue FROM C_Order WHERE C_Order_ID=@C_Order_ID@);
      }
    }
    // Derivation: cBpartnerLocationId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cBpartnerLocationId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.cBpartnerLocationId);
        }
      } else {
        event.setCurrentState(prop, context.cBpartnerLocationId);
      }
    }
    // Derivation: iseditlinenetamt (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("iseditlinenetamt");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, N);
        }
      } else {
        event.setCurrentState(prop, N);
      }
    }
    // Derivation: adOrgId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adOrgId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.organization);
        }
      } else {
        event.setCurrentState(prop, context.organization);
      }
    }
    // Derivation: bomParentId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("bomParentId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: cOrderDiscountId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cOrderDiscountId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: mOfferId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("mOfferId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: isDescription (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isDescription");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, N);
        }
      } else {
        event.setCurrentState(prop, N);
      }
    }
    // Derivation: sResourceAssignmentId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("sResourceAssignmentId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: priceLimit (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("priceLimit");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, 0);
        }
      } else {
        event.setCurrentState(prop, 0);
      }
    }
    // Derivation: cCurrencyId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cCurrencyId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.cCurrencyId);
        }
      } else {
        event.setCurrentState(prop, context.cCurrencyId);
      }
    }
    // Derivation: dateInvoiced (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("dateInvoiced");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: dateDelivered (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("dateDelivered");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: cOrderId (fromParent) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cOrderId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, cOrder.cOrderId);
        }
      } else {
        event.setCurrentState(prop, cOrder.cOrderId);
      }
    }
    // Derivation: isActive (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isActive");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, true);
        }
      } else {
        event.setCurrentState(prop, true);
      }
    }
    // Derivation: adClientId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adClientId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.client);
        }
      } else {
        event.setCurrentState(prop, context.client);
      }
    }
    // Derivation: cOrderLineId (sequence) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cOrderLineId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, );
        }
      } else {
        event.setCurrentState(prop, );
      }
    }
  }
}
