// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Schema version: 
// Checksum: 
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.event;

import javax.enterprise.event.Observes;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;
import org.openbravo.dal.core.OBContext;
import com.etendoerp.go.dto.COrderTaxDTO;

/**
 * Event handler for cOrderTax entity derivations.
 *
 * Handles automatic field derivation on create and update events.
 */
public class COrderTaxDerivationHandler extends EntityPersistenceEventObserver {

  private static final Entity[] ENTITIES = {
    ModelProvider.getInstance().getEntity(cOrderTax.ENTITY_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return ENTITIES;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(org.openbravo.client.kernel.event.EntityPersistenceEvent event) {
    // Derivation: cOrderId (fromParent) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cOrderId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, cOrder.cOrderId);
        }
      } else {
        event.setCurrentState(prop, cOrder.cOrderId);
      }
    }
    // Derivation: isActive (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isActive");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, true);
        }
      } else {
        event.setCurrentState(prop, true);
      }
    }
    // Derivation: adClientId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adClientId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.client);
        }
      } else {
        event.setCurrentState(prop, context.client);
      }
    }
    // Derivation: adOrgId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adOrgId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.organization);
        }
      } else {
        event.setCurrentState(prop, context.organization);
      }
    }
    // Derivation: cOrderTaxId (sequence) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cOrderTaxId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, );
        }
      } else {
        event.setCurrentState(prop, );
      }
    }
  }
}
