// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Schema version: 
// Checksum: 
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.event;

import javax.enterprise.event.Observes;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;
import org.openbravo.dal.core.OBContext;
import com.etendoerp.go.dto.COrderlineProductrelationDTO;

/**
 * Event handler for cOrderlineProductrelation entity derivations.
 *
 * Handles automatic field derivation on create and update events.
 */
public class COrderlineProductrelationDerivationHandler extends EntityPersistenceEventObserver {

  private static final Entity[] ENTITIES = {
    ModelProvider.getInstance().getEntity(cOrderlineProductrelation.ENTITY_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return ENTITIES;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(org.openbravo.client.kernel.event.EntityPersistenceEvent event) {
    // Derivation: amount (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("amount");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, 0);
        }
      } else {
        event.setCurrentState(prop, 0);
      }
    }
    // Derivation: quantity (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("quantity");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, 0);
        }
      } else {
        event.setCurrentState(prop, 0);
      }
    }
  }
}
