// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Schema version: 
// Checksum: 
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.event;

import javax.enterprise.event.Observes;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;
import org.openbravo.dal.core.OBContext;
import com.etendoerp.go.dto.COrderDTO;

/**
 * Event handler for cOrder entity derivations.
 *
 * Handles automatic field derivation on create and update events.
 */
public class COrderDerivationHandler extends EntityPersistenceEventObserver {

  private static final Entity[] ENTITIES = {
    ModelProvider.getInstance().getEntity(cOrder.ENTITY_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return ENTITIES;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(org.openbravo.client.kernel.event.EntityPersistenceEvent event) {
    // Derivation: cDocTypeId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cDocTypeId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, doctype.salesOrder);
        }
      } else {
        event.setCurrentState(prop, doctype.salesOrder);
      }
    }
    // Derivation: replacementorderId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("replacementorderId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: isSelfService (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isSelfService");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, false);
        }
      } else {
        event.setCurrentState(prop, false);
      }
    }
    // Derivation: isSelected (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isSelected");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, false);
        }
      } else {
        event.setCurrentState(prop, false);
      }
    }
    // Derivation: posted (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("posted");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, 'N');
        }
      } else {
        event.setCurrentState(prop, 'N');
      }
    }
    // Derivation: isSotrx (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isSotrx");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.isSotrx);
        }
      } else {
        event.setCurrentState(prop, context.isSotrx);
      }
    }
    // Derivation: datePrinted (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("datePrinted");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: processed (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("processed");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, false);
        }
      } else {
        event.setCurrentState(prop, false);
      }
    }
    // Derivation: processing (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("processing");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, false);
        }
      } else {
        event.setCurrentState(prop, false);
      }
    }
    // Derivation: cOrderId (sequence) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cOrderId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, );
        }
      } else {
        event.setCurrentState(prop, );
      }
    }
    // Derivation: isPrinted (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isPrinted");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, false);
        }
      } else {
        event.setCurrentState(prop, false);
      }
    }
    // Derivation: isInvoiced (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isInvoiced");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, false);
        }
      } else {
        event.setCurrentState(prop, false);
      }
    }
    // Derivation: isActive (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isActive");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, true);
        }
      } else {
        event.setCurrentState(prop, true);
      }
    }
    // Derivation: adClientId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adClientId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.client);
        }
      } else {
        event.setCurrentState(prop, context.client);
      }
    }
  }
}
