// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Schema version: 
// Checksum: 
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.event;

import javax.enterprise.event.Observes;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;
import org.openbravo.dal.core.OBContext;
import com.etendoerp.go.dto.FinPaymentDetailVDTO;

/**
 * Event handler for finPaymentDetailV entity derivations.
 *
 * Handles automatic field derivation on create and update events.
 */
public class FinPaymentDetailVDerivationHandler extends EntityPersistenceEventObserver {

  private static final Entity[] ENTITIES = {
    ModelProvider.getInstance().getEntity(finPaymentDetailV.ENTITY_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return ENTITIES;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(org.openbravo.client.kernel.event.EntityPersistenceEvent event) {
    // Derivation: finPaymentmethodId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("finPaymentmethodId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: finFinancialAccountId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("finFinancialAccountId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: cCurrencyId (fromParent) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cCurrencyId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, finPaymentSchedOrdV.cCurrencyId);
        }
      } else {
        event.setCurrentState(prop, finPaymentSchedOrdV.cCurrencyId);
      }
    }
    // Derivation: paymentno (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("paymentno");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, '');
        }
      } else {
        event.setCurrentState(prop, '');
      }
    }
    // Derivation: finaccCurrencyId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("finaccCurrencyId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: finPaymentSchedOrdVId (fromParent) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("finPaymentSchedOrdVId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, finPaymentSchedOrdV.finPaymentSchedOrdVId);
        }
      } else {
        event.setCurrentState(prop, finPaymentSchedOrdV.finPaymentSchedOrdVId);
      }
    }
    // Derivation: isactive (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isactive");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, true);
        }
      } else {
        event.setCurrentState(prop, true);
      }
    }
    // Derivation: orderno (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("orderno");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, '');
        }
      } else {
        event.setCurrentState(prop, '');
      }
    }
    // Derivation: adOrgId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adOrgId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.organization);
        }
      } else {
        event.setCurrentState(prop, context.organization);
      }
    }
    // Derivation: finPaymentDetailVId (sequence) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("finPaymentDetailVId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, );
        }
      } else {
        event.setCurrentState(prop, );
      }
    }
    // Derivation: invoiceno (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("invoiceno");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, '');
        }
      } else {
        event.setCurrentState(prop, '');
      }
    }
    // Derivation: invoicedamt (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("invoicedamt");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, 0);
        }
      } else {
        event.setCurrentState(prop, 0);
      }
    }
    // Derivation: cBpartnerId (fromParent) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cBpartnerId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, cOrder.cBpartnerId);
        }
      } else {
        event.setCurrentState(prop, cOrder.cBpartnerId);
      }
    }
    // Derivation: adClientId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adClientId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.client);
        }
      } else {
        event.setCurrentState(prop, context.client);
      }
    }
  }
}
