// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Schema version: 
// Checksum: 
// Generated: 2026-03-05T19:18:00.136Z
package com.etendoerp.go.event;

import javax.enterprise.event.Observes;
import org.openbravo.base.model.Entity;
import org.openbravo.base.model.ModelProvider;
import org.openbravo.base.model.Property;
import org.openbravo.client.kernel.event.EntityNewEvent;
import org.openbravo.client.kernel.event.EntityPersistenceEventObserver;
import org.openbravo.client.kernel.event.EntityUpdateEvent;
import org.openbravo.dal.core.OBContext;
import com.etendoerp.go.dto.MSolReservedStockVDTO;

/**
 * Event handler for mSolReservedStockV entity derivations.
 *
 * Handles automatic field derivation on create and update events.
 */
public class MSolReservedStockVDerivationHandler extends EntityPersistenceEventObserver {

  private static final Entity[] ENTITIES = {
    ModelProvider.getInstance().getEntity(mSolReservedStockV.ENTITY_NAME)
  };

  @Override
  protected Entity[] getObservedEntities() {
    return ENTITIES;
  }

  public void onNew(@Observes EntityNewEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  public void onUpdate(@Observes EntityUpdateEvent event) {
    if (!isValidEvent(event)) {
      return;
    }
    applyDerivations(event);
  }

  private void applyDerivations(org.openbravo.client.kernel.event.EntityPersistenceEvent event) {
    // Derivation: isactive (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("isactive");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, true);
        }
      } else {
        event.setCurrentState(prop, true);
      }
    }
    // Derivation: mSolReservedStockVId (sequence) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("mSolReservedStockVId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, );
        }
      } else {
        event.setCurrentState(prop, );
      }
    }
    // Derivation: adClientId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adClientId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.client);
        }
      } else {
        event.setCurrentState(prop, context.client);
      }
    }
    // Derivation: adOrgId (fromConfig) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("adOrgId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, context.organization);
        }
      } else {
        event.setCurrentState(prop, context.organization);
      }
    }
    // Derivation: mReservationStockId (computed) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("mReservationStockId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, null);
        }
      } else {
        event.setCurrentState(prop, null);
      }
    }
    // Derivation: cOrderlineId (fromParent) — maps to /
    {
      final Property prop = ENTITIES[0].getProperty("cOrderlineId");
      if (event instanceof EntityUpdateEvent) {
        EntityUpdateEvent updateEvent = (EntityUpdateEvent) event;
        if (updateEvent.getCurrentState(prop) == updateEvent.getPreviousState(prop)) {
          // Hibernate dirty check guard — skip if unchanged
        } else {
          event.setCurrentState(prop, cOrderLine.cOrderLineId);
        }
      } else {
        event.setCurrentState(prop, cOrderLine.cOrderLineId);
      }
    }
  }
}
