// GENERATED BY SCHEMA FORGE — DO NOT EDIT
// Generated: 2026-03-05T20:16:12.646Z
package com.etendoerp.go.salesorder.process;

import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openbravo.base.exception.OBException;
import org.openbravo.dal.service.OBDal;
import org.openbravo.erpCommon.utility.OBError;
import org.openbravo.scheduling.ProcessBundle;
import org.openbravo.service.db.DalBaseProcess;
import org.openbravo.model.common.order.Order;

/**
 * DAL Process: CopyLinesProcess
 *
 * Entity: cOrder (Order)
 * Preconditions: 2
 * Steps: 4
 */
public class CopyLinesProcess extends DalBaseProcess {

  private static final Logger log = LogManager.getLogger();

  @Override
  protected void doExecute(ProcessBundle bundle) throws Exception {
    try {
      final Map<String, Object> params = bundle.getParams();
      final String recordId = (String) params.get("recordId");

      final Order entity = OBDal.getInstance().get(Order.class, recordId);
      if (entity == null) {
        throw new OBException("Order not found with ID: " + recordId);
      }

      // --- Preconditions ---
      // PRE-CL-001: Target order must be in Draft status to copy lines into it
      // Assertion: order.docStatus == 'DR'
      // TODO(vertical-slice): implement precondition check
      // PRE-CL-002: At least one source order must be selected
      // Assertion: sourceOrderIds.length > 0
      // TODO(vertical-slice): implement precondition check

      // --- Process Steps ---
      // Step 1: validateSourceOrders (validate)
      // Verify all selected source orders exist and are accessible
      // TODO(vertical-slice): implement step logic
      // Step 2: copyLinesFromSources (forEach)
      // Iterate over each source order and copy its lines to the target order, applying hook-based transformations for product, quantity, attributes, prices, and taxes
      // TODO(vertical-slice): implement step logic
      // Step 3: explodeBomProducts (forEach)
      // For any copied line with a non-stocked BOM product, replace it with its component lines
      // TODO(vertical-slice): implement step logic
      // Step 4: recalculateOrderTotals (compute)
      // Recalculate the target order header totals after all lines have been copied
      // TODO(vertical-slice): implement step logic

      OBDal.getInstance().flush();

      final OBError msg = new OBError();
      msg.setType("Success");
      msg.setTitle("Process completed");
      bundle.setResult(msg);

    } catch (OBException e) {
      log.error("Process failed", e);
      final OBError msg = new OBError();
      msg.setType("Error");
      msg.setMessage(e.getMessage());
      bundle.setResult(msg);
      OBDal.getInstance().rollbackAndClose();
    }
  }
}
