/*
 * EtendoGo API
 * REST API for the EtendoGo mobile application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.etendoerp.etendogo.rest.contract.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ProductScanResponse
 */
@JsonPropertyOrder({
  ProductScanResponse.JSON_PROPERTY_PRODUCT_ID,
  ProductScanResponse.JSON_PROPERTY_NAME,
  ProductScanResponse.JSON_PROPERTY_PRICE,
  ProductScanResponse.JSON_PROPERTY_STOCK,
  ProductScanResponse.JSON_PROPERTY_FOUND
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-04T14:52:57.488707-03:00[America/Argentina/Cordoba]")
public class ProductScanResponse {
  public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
  private String productId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_STOCK = "stock";
  private Integer stock;

  public static final String JSON_PROPERTY_FOUND = "found";
  private Boolean found;

  public ProductScanResponse() { 
  }

  public ProductScanResponse productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Product identifier
   * @return productId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(String productId) {
    this.productId = productId;
  }


  public ProductScanResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Product name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ProductScanResponse price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Product price
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public ProductScanResponse stock(Integer stock) {
    this.stock = stock;
    return this;
  }

   /**
   * Stock quantity
   * @return stock
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStock() {
    return stock;
  }


  @JsonProperty(JSON_PROPERTY_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStock(Integer stock) {
    this.stock = stock;
  }


  public ProductScanResponse found(Boolean found) {
    this.found = found;
    return this;
  }

   /**
   * Whether the product was found
   * @return found
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FOUND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getFound() {
    return found;
  }


  @JsonProperty(JSON_PROPERTY_FOUND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFound(Boolean found) {
    this.found = found;
  }


  /**
   * Return true if this ProductScanResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductScanResponse productScanResponse = (ProductScanResponse) o;
    return Objects.equals(this.productId, productScanResponse.productId) &&
        Objects.equals(this.name, productScanResponse.name) &&
        Objects.equals(this.price, productScanResponse.price) &&
        Objects.equals(this.stock, productScanResponse.stock) &&
        Objects.equals(this.found, productScanResponse.found);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, name, price, stock, found);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductScanResponse {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("    found: ").append(toIndentedString(found)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `productId` to the URL query string
    if (getProductId() != null) {
      joiner.add(String.format("%sproductId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getProductId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format("%sprice%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrice()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `stock` to the URL query string
    if (getStock() != null) {
      joiner.add(String.format("%sstock%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStock()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `found` to the URL query string
    if (getFound() != null) {
      joiner.add(String.format("%sfound%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFound()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

