/*
 * EtendoGo API
 * REST API for the EtendoGo mobile application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.etendoerp.etendogo.rest.contract.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ProductScanRequest
 */
@JsonPropertyOrder({
  ProductScanRequest.JSON_PROPERTY_SEARCH_KEY,
  ProductScanRequest.JSON_PROPERTY_WAREHOUSE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-04T14:52:57.488707-03:00[America/Argentina/Cordoba]")
public class ProductScanRequest {
  public static final String JSON_PROPERTY_SEARCH_KEY = "searchKey";
  private String searchKey;

  public static final String JSON_PROPERTY_WAREHOUSE_ID = "warehouseId";
  private String warehouseId;

  public ProductScanRequest() { 
  }

  public ProductScanRequest searchKey(String searchKey) {
    this.searchKey = searchKey;
    return this;
  }

   /**
   * Barcode or product identifier to search for
   * @return searchKey
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEARCH_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSearchKey() {
    return searchKey;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSearchKey(String searchKey) {
    this.searchKey = searchKey;
  }


  public ProductScanRequest warehouseId(String warehouseId) {
    this.warehouseId = warehouseId;
    return this;
  }

   /**
   * Warehouse context for the search
   * @return warehouseId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WAREHOUSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWarehouseId() {
    return warehouseId;
  }


  @JsonProperty(JSON_PROPERTY_WAREHOUSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarehouseId(String warehouseId) {
    this.warehouseId = warehouseId;
  }


  /**
   * Return true if this ProductScanRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductScanRequest productScanRequest = (ProductScanRequest) o;
    return Objects.equals(this.searchKey, productScanRequest.searchKey) &&
        Objects.equals(this.warehouseId, productScanRequest.warehouseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchKey, warehouseId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductScanRequest {\n");
    sb.append("    searchKey: ").append(toIndentedString(searchKey)).append("\n");
    sb.append("    warehouseId: ").append(toIndentedString(warehouseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `searchKey` to the URL query string
    if (getSearchKey() != null) {
      joiner.add(String.format("%ssearchKey%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSearchKey()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `warehouseId` to the URL query string
    if (getWarehouseId() != null) {
      joiner.add(String.format("%swarehouseId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWarehouseId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

